window._MII_EMPLOYEES = [
  {"employee_number": "K960", "name": "A Clifford", "trade": "", "is_active": true},
  {"employee_number": "AGY0001", "name": "A Oak", "trade": "", "is_active": true},
  {"employee_number": "L366", "name": "A Scott", "trade": "", "is_active": true},
  {"employee_number": "M633", "name": "Aaron Bundy", "trade": "", "is_active": true},
  {"employee_number": "AGY0002", "name": "Aaron Williams", "trade": "", "is_active": true},
  {"employee_number": "M059", "name": "Adam Chard", "trade": "Mech Fitter", "is_active": true},
  {"employee_number": "AGY0003", "name": "Adam Japp", "trade": "", "is_active": true},
  {"employee_number": "L682", "name": "Adam Miller", "trade": "", "is_active": true},
  {"employee_number": "AGY0004", "name": "Adrian Downes", "trade": "", "is_active": true},
  {"employee_number": "AGY0005", "name": "Alan Bell", "trade": "", "is_active": true},
  {"employee_number": "L113", "name": "Alan Lewis", "trade": "", "is_active": true},
  {"employee_number": "AGY0006", "name": "Alan Richards", "trade": "", "is_active": true},
  {"employee_number": "AGY0007", "name": "Alex Jenkins", "trade": "", "is_active": true},
  {"employee_number": "AGY0008", "name": "Alex Mercher", "trade": "", "is_active": true},
  {"employee_number": "AGY0009", "name": "Alex Wright", "trade": "", "is_active": true},
  {"employee_number": "M349", "name": "Alun Wigley", "trade": "Mech Fitter", "is_active": true},
  {"employee_number": "L927", "name": "Andrew Hathaway", "trade": "", "is_active": true},
  {"employee_number": "L261", "name": "Andrew Davies", "trade": "", "is_active": true},
  {"employee_number": "K675", "name": "Andrew Evans", "trade": "", "is_active": true},
  {"employee_number": "M480", "name": "Andrew Hughes", "trade": "Welder", "is_active": true},
  {"employee_number": "K822", "name": "Andrew Jenkins", "trade": "Pipe fitter", "is_active": true},
  {"employee_number": "L488", "name": "Andrew Lewis", "trade": "Electrician", "is_active": true},
  {"employee_number": "L258", "name": "Andrew Manning", "trade": "Fabricator Welder", "is_active": true},
  {"employee_number": "AGY0011", "name": "Andrew Morgan", "trade": "", "is_active": true},
  {"employee_number": "AGY0012", "name": "Andrew Stewart", "trade": "", "is_active": true},
  {"employee_number": "L585", "name": "Andrew Stolzenburg", "trade": "Electrician", "is_active": true},
  {"employee_number": "J683", "name": "Andy Baron", "trade": "", "is_active": true},
  {"employee_number": "J482", "name": "Andy McBride", "trade": "", "is_active": true},
  {"employee_number": "J987", "name": "Andy Viggers", "trade": "Electrician", "is_active": true},
  {"employee_number": "AGY0013", "name": "Anthony Richards", "trade": "", "is_active": true},
  {"employee_number": "AGY0014", "name": "Ashley Breeze", "trade": "Mech Fitter", "is_active": true},
  {"employee_number": "J579", "name": "B Ronan", "trade": "", "is_active": true},
  {"employee_number": "AGY0015", "name": "Barry Jamie", "trade": "Store man", "is_active": true},
  {"employee_number": "AGY0016", "name": "Barry Watkins", "trade": "", "is_active": true},
  {"employee_number": "AGY0017", "name": "Ben Edwards", "trade": "", "is_active": true},
  {"employee_number": "AGY0018", "name": "Ben Harvey", "trade": "", "is_active": true},
  {"employee_number": "M534", "name": "Ben Jenkins", "trade": "", "is_active": true},
  {"employee_number": "AGY0019", "name": "Ben Jennings", "trade": "", "is_active": true},
  {"employee_number": "S022", "name": "Ben McCambridge", "trade": "", "is_active": true},
  {"employee_number": "L589", "name": "Ben Newman", "trade": "", "is_active": true},
  {"employee_number": "M136", "name": "Ben Page", "trade": "", "is_active": true},
  {"employee_number": "AGY0020", "name": "Ben Reynolds", "trade": "", "is_active": true},
  {"employee_number": "K976", "name": "Billy Bull", "trade": "", "is_active": true},
  {"employee_number": "AGY0021", "name": "Billy Davies", "trade": "", "is_active": true},
  {"employee_number": "AGY0022", "name": "Brandon Hughes", "trade": "", "is_active": true},
  {"employee_number": "M406", "name": "Brendan Tierney", "trade": "Rigger", "is_active": true},
  {"employee_number": "AGY0023", "name": "Brian Abdie", "trade": "", "is_active": true},
  {"employee_number": "AGY0024", "name": "Brian Arnesen", "trade": "Managing Director", "is_active": true},
  {"employee_number": "L946", "name": "Brian Chard", "trade": "", "is_active": true},
  {"employee_number": "AGY0025", "name": "Brian Corish", "trade": "", "is_active": true},
  {"employee_number": "L548", "name": "Brian Covill", "trade": "Mech Fitter", "is_active": true},
  {"employee_number": "AGY0026", "name": "Brian Cullen", "trade": "", "is_active": true},
  {"employee_number": "M785", "name": "Bruce Robertson", "trade": "Mech Fitter", "is_active": true},
  {"employee_number": "L024", "name": "Cain Thomas", "trade": "Fabricator Welder", "is_active": true},
  {"employee_number": "AGY0027", "name": "Callum Manley", "trade": "", "is_active": true},
  {"employee_number": "AGY0028", "name": "Callum Oglesby", "trade": "", "is_active": true},
  {"employee_number": "H032", "name": "Carl Cleverly", "trade": "", "is_active": true},
  {"employee_number": "L726", "name": "Carl Dowsell", "trade": "", "is_active": true},
  {"employee_number": "M717", "name": "Carl Falvey", "trade": "", "is_active": true},
  {"employee_number": "K394", "name": "Carl Jones", "trade": "Pipe Fitter", "is_active": true},
  {"employee_number": "M347", "name": "Chris Boyd", "trade": "Apprentice", "is_active": true},
  {"employee_number": "L952", "name": "Chris Campbell", "trade": "Mech Fitter", "is_active": true},
  {"employee_number": "M120", "name": "Chris Holman", "trade": "", "is_active": true},
  {"employee_number": "L438", "name": "Chris Lenahan", "trade": "", "is_active": true},
  {"employee_number": "L429", "name": "Chris Morgan", "trade": "Welder", "is_active": true},
  {"employee_number": "M348", "name": "Chris Morris", "trade": "", "is_active": true},
  {"employee_number": "AGY0029", "name": "Chris Phillips", "trade": "Mech Fitter", "is_active": true},
  {"employee_number": "M302", "name": "Chris Pye", "trade": "", "is_active": true},
  {"employee_number": "AGY0030", "name": "Chris Scott", "trade": "", "is_active": true},
  {"employee_number": "AGY0031", "name": "Chris Stokes", "trade": "", "is_active": true},
  {"employee_number": "L398", "name": "Chris Thomas", "trade": "Mech Fitter", "is_active": true},
  {"employee_number": "AGY0032", "name": "Chris Wilson", "trade": "", "is_active": true},
  {"employee_number": "K905", "name": "Christian Francis", "trade": "", "is_active": true},
  {"employee_number": "AGY0033", "name": "Christopher Cole", "trade": "", "is_active": true},
  {"employee_number": "M581", "name": "Ciaran O'Connor", "trade": "", "is_active": true},
  {"employee_number": "L771", "name": "Cliff Quinn", "trade": "Rigger", "is_active": true},
  {"employee_number": "L915", "name": "Colin Barnett", "trade": "", "is_active": true},
  {"employee_number": "AGY0034", "name": "Colin Hammond", "trade": "", "is_active": true},
  {"employee_number": "AGY0035", "name": "Colin Neale", "trade": "", "is_active": true},
  {"employee_number": "M557", "name": "Colin Rees", "trade": "", "is_active": true},
  {"employee_number": "K686", "name": "Conrad Morris", "trade": "Mech Fitter", "is_active": true},
  {"employee_number": "M335", "name": "Corey Lynch", "trade": "", "is_active": true},
  {"employee_number": "M158", "name": "Cory Burnell-Jones", "trade": "", "is_active": true},
  {"employee_number": "AGY0036", "name": "Coulton Jamie", "trade": "", "is_active": true},
  {"employee_number": "AGY0037", "name": "Craig Daunter", "trade": "", "is_active": true},
  {"employee_number": "L872", "name": "Craig Hargreaves", "trade": "", "is_active": true},
  {"employee_number": "AGY0038", "name": "Craig Jones", "trade": "", "is_active": true},
  {"employee_number": "M142", "name": "Craig Madden", "trade": "", "is_active": true},
  {"employee_number": "AGY0039", "name": "Craig Moulton", "trade": "Welder", "is_active": true},
  {"employee_number": "J688", "name": "Craig Richards", "trade": "Pipe Fitter", "is_active": true},
  {"employee_number": "L021", "name": "Craig Rogers", "trade": "Mech Fitter", "is_active": true},
  {"employee_number": "K326", "name": "Craig Williams", "trade": "Welder", "is_active": true},
  {"employee_number": "AGY0040", "name": "Curtis Bellew", "trade": "", "is_active": true},
  {"employee_number": "M677", "name": "Curtis Williams", "trade": "", "is_active": true},
  {"employee_number": "AGY0041", "name": "Dai Rees", "trade": "", "is_active": true},
  {"employee_number": "L423", "name": "Dai Vance Daniel", "trade": "", "is_active": true},
  {"employee_number": "AGY0042", "name": "Dale Caruana", "trade": "", "is_active": true},
  {"employee_number": "K106", "name": "Dale Henley", "trade": "Pipe Fitter", "is_active": true},
  {"employee_number": "AGY0043", "name": "Dale Legg", "trade": "", "is_active": true},
  {"employee_number": "AGY0044", "name": "Dale Robinson", "trade": "Rigger", "is_active": true},
  {"employee_number": "L776", "name": "Damien Canham", "trade": "", "is_active": true},
  {"employee_number": "M351", "name": "Daniel Evans", "trade": "", "is_active": true},
  {"employee_number": "AGY0045", "name": "Daniel Eaton", "trade": "", "is_active": true},
  {"employee_number": "AGY0046", "name": "Daniel Oglesby", "trade": "", "is_active": true},
  {"employee_number": "AGY0047", "name": "Dario Beslija", "trade": "", "is_active": true},
  {"employee_number": "K091", "name": "Darrell Thomas", "trade": "Supervisor", "is_active": true},
  {"employee_number": "AGY0048", "name": "Dave Jackson", "trade": "Manager", "is_active": true},
  {"employee_number": "AGY0049", "name": "Dave Mazey", "trade": "", "is_active": true},
  {"employee_number": "K922", "name": "David Barlow", "trade": "", "is_active": true},
  {"employee_number": "M318", "name": "David Bevan", "trade": "", "is_active": true},
  {"employee_number": "L919", "name": "David C Davies", "trade": "", "is_active": true},
  {"employee_number": "AGY0051", "name": "David C Lloyd", "trade": "Mech Fitter", "is_active": true},
  {"employee_number": "AGY0052", "name": "David Evans", "trade": "", "is_active": true},
  {"employee_number": "AGY0053", "name": "David Gooding", "trade": "", "is_active": true},
  {"employee_number": "AGY0054", "name": "David John", "trade": "Mech Fitter", "is_active": true},
  {"employee_number": "AGY0055", "name": "David Knee", "trade": "", "is_active": true},
  {"employee_number": "AGY0056", "name": "David Manley", "trade": "", "is_active": true},
  {"employee_number": "AGY0057", "name": "David Miller", "trade": "Welder", "is_active": true},
  {"employee_number": "AGY0058", "name": "David Thomas", "trade": "", "is_active": true},
  {"employee_number": "AGY0059", "name": "David Thomas", "trade": "", "is_active": true},
  {"employee_number": "M505", "name": "David-Craig Allen", "trade": "Mech Fitter", "is_active": true},
  {"employee_number": "M067", "name": "Dean Cronin", "trade": "Electrical", "is_active": true},
  {"employee_number": "AGY0060", "name": "Dean Hurley", "trade": "", "is_active": true},
  {"employee_number": "M641", "name": "Dean Lewis", "trade": "", "is_active": true},
  {"employee_number": "AGY0061", "name": "Dean Thomas", "trade": "", "is_active": true},
  {"employee_number": "AGY0062", "name": "Deon Thomas", "trade": "", "is_active": true},
  {"employee_number": "AGY0063", "name": "Derek Miles", "trade": "", "is_active": true},
  {"employee_number": "K151", "name": "Deri Hewitson", "trade": "", "is_active": true},
  {"employee_number": "AGY0064", "name": "Dillon Chapman", "trade": "", "is_active": true},
  {"employee_number": "M304", "name": "Dilwyn Price", "trade": "", "is_active": true},
  {"employee_number": "AGY0065", "name": "Dion Hunter", "trade": "", "is_active": true},
  {"employee_number": "AGY0066", "name": "Doug Jones", "trade": "Fitter", "is_active": true},
  {"employee_number": "S051", "name": "Drew Davies", "trade": "", "is_active": true},
  {"employee_number": "AGY0067", "name": "Ellis Channing", "trade": "", "is_active": true},
  {"employee_number": "M538", "name": "Elmore Evans", "trade": "", "is_active": true},
  {"employee_number": "AGY0068", "name": "Ethen Simpson", "trade": "", "is_active": true},
  {"employee_number": "AGY0069", "name": "Flynn Lewis", "trade": "", "is_active": true},
  {"employee_number": "AGY0070", "name": "G Rowe", "trade": "", "is_active": true},
  {"employee_number": "AGY0071", "name": "Gareth Edwards", "trade": "", "is_active": true},
  {"employee_number": "AGY0072", "name": "Gareth Manley", "trade": "", "is_active": true},
  {"employee_number": "AGY0073", "name": "Gareth Walters", "trade": "", "is_active": true},
  {"employee_number": "AGY0074", "name": "Gareth Watkins", "trade": "", "is_active": true},
  {"employee_number": "AGY0075", "name": "Gary Dawson", "trade": "", "is_active": true},
  {"employee_number": "AGY0076", "name": "Gareth Devonald", "trade": "Fitter", "is_active": true},
  {"employee_number": "AGY0077", "name": "Gary Journeaux", "trade": "", "is_active": true},
  {"employee_number": "K972", "name": "Gary Shergold", "trade": "", "is_active": true},
  {"employee_number": "AGY0078", "name": "Gary Thomas", "trade": "", "is_active": true},
  {"employee_number": "AGY0079", "name": "Gavin O'Neill", "trade": "", "is_active": true},
  {"employee_number": "L466", "name": "Geoff Davies", "trade": "Electrician", "is_active": true},
  {"employee_number": "AGY0080", "name": "Gerry Deere", "trade": "", "is_active": true},
  {"employee_number": "M069", "name": "Gethin Davies", "trade": "Electrician", "is_active": true},
  {"employee_number": "L808", "name": "Gibson Alphonse", "trade": "Mate", "is_active": true},
  {"employee_number": "K954", "name": "Glyn Perry", "trade": "", "is_active": true},
  {"employee_number": "L864", "name": "Goff Williams", "trade": "", "is_active": true},
  {"employee_number": "AGY0081", "name": "Gordon Yeates", "trade": "", "is_active": true},
  {"employee_number": "L009", "name": "Graham Evans", "trade": "Mech Fitter", "is_active": true},
  {"employee_number": "L734", "name": "Graham Phillips", "trade": "", "is_active": true},
  {"employee_number": "AGY0082", "name": "Greg Clancy", "trade": "", "is_active": true},
  {"employee_number": "L843", "name": "Greg Jones", "trade": "Fabricator", "is_active": true},
  {"employee_number": "AGY0083", "name": "Greg Meyrick", "trade": "", "is_active": true},
  {"employee_number": "AGY0084", "name": "Gwyndaf Jones", "trade": "", "is_active": true},
  {"employee_number": "AGY0085", "name": "Harry Vaux", "trade": "", "is_active": true},
  {"employee_number": "AGY0086", "name": "Hayley Dabbs", "trade": "Sales Ledger", "is_active": true},
  {"employee_number": "AGY0087", "name": "Hudson Nimrod", "trade": "", "is_active": true},
  {"employee_number": "L954", "name": "Huw Williams", "trade": "Rigger", "is_active": true},
  {"employee_number": "AGY0088", "name": "Hywel Lee", "trade": "", "is_active": true},
  {"employee_number": "AGY0089", "name": "Ian Cabral", "trade": "", "is_active": true},
  {"employee_number": "M432", "name": "Ian Cooper", "trade": "Fitter", "is_active": true},
  {"employee_number": "AGY0090", "name": "Ian George", "trade": "Electrician", "is_active": true},
  {"employee_number": "AGY0091", "name": "Ian Hill", "trade": "", "is_active": true},
  {"employee_number": "K073", "name": "Ian Hopkins", "trade": "Co-ordinator", "is_active": true},
  {"employee_number": "AGY0092", "name": "Ian Marsh", "trade": "", "is_active": true},
  {"employee_number": "M655", "name": "Ian Minton", "trade": "", "is_active": true},
  {"employee_number": "M363", "name": "Ian Roblin", "trade": "", "is_active": true},
  {"employee_number": "L713", "name": "Ieuan Lewis", "trade": "", "is_active": true},
  {"employee_number": "L624", "name": "Ivel Reed", "trade": "", "is_active": true},
  {"employee_number": "AGY0093", "name": "Iwan Phillips", "trade": "", "is_active": true},
  {"employee_number": "AGY0094", "name": "Jac Parker", "trade": "", "is_active": true},
  {"employee_number": "AGY0095", "name": "Jack Dacey", "trade": "", "is_active": true},
  {"employee_number": "AGY0096", "name": "Jack Rawlings", "trade": "", "is_active": true},
  {"employee_number": "L860", "name": "Jack Rowles", "trade": "", "is_active": true},
  {"employee_number": "M181", "name": "James Keary", "trade": "", "is_active": true},
  {"employee_number": "AGY0097", "name": "James Minton", "trade": "", "is_active": true},
  {"employee_number": "AGY0098", "name": "James Stacey", "trade": "Designer", "is_active": true},
  {"employee_number": "L679", "name": "James Williams", "trade": "", "is_active": true},
  {"employee_number": "AGY0099", "name": "Jamie Locke", "trade": "", "is_active": true},
  {"employee_number": "L137", "name": "Jamie Morris", "trade": "Fabricator Welder", "is_active": true},
  {"employee_number": "AGY0100", "name": "Jamie Ryan", "trade": "", "is_active": true},
  {"employee_number": "L631", "name": "Jason Bryce", "trade": "Mech Fitter", "is_active": true},
  {"employee_number": "AGY0101", "name": "Jason Hughes", "trade": "", "is_active": true},
  {"employee_number": "AGY0102", "name": "Jason McCormack", "trade": "", "is_active": true},
  {"employee_number": "AGY0103", "name": "Jay Roberts", "trade": "", "is_active": true},
  {"employee_number": "AGY0104", "name": "Jed Hamer Thomas", "trade": "", "is_active": true},
  {"employee_number": "AGY0105", "name": "Jed Hamer-Thomas", "trade": "", "is_active": true},
  {"employee_number": "M463", "name": "Jeff Boyes", "trade": "Mech Fitter", "is_active": true},
  {"employee_number": "L649", "name": "Jeff Eger", "trade": "", "is_active": true},
  {"employee_number": "AGY0106", "name": "Jeff Staples", "trade": "", "is_active": true},
  {"employee_number": "L943", "name": "Jeffrey Williams", "trade": "Welder", "is_active": true},
  {"employee_number": "K118", "name": "Jeremy Brannigan", "trade": "", "is_active": true},
  {"employee_number": "K971", "name": "John Batty", "trade": "", "is_active": true},
  {"employee_number": "L680", "name": "John Berry", "trade": "", "is_active": true},
  {"employee_number": "AGY0107", "name": "John Bhambra", "trade": "", "is_active": true},
  {"employee_number": "J658", "name": "John Clapp", "trade": "", "is_active": true},
  {"employee_number": "AGY0108", "name": "John Collins", "trade": "", "is_active": true},
  {"employee_number": "AGY0109", "name": "John David", "trade": "", "is_active": true},
  {"employee_number": "AGY0110", "name": "John Evans", "trade": "HSE Advisor", "is_active": true},
  {"employee_number": "AGY0111", "name": "John Gore", "trade": "", "is_active": true},
  {"employee_number": "AGY0112", "name": "John Lake", "trade": "", "is_active": true},
  {"employee_number": "AGY0113", "name": "John Paul Meli", "trade": "", "is_active": true},
  {"employee_number": "AGY0114", "name": "John Piontecki", "trade": "Chargehand", "is_active": true},
  {"employee_number": "K529", "name": "John Watkins", "trade": "Mech Fitter", "is_active": true},
  {"employee_number": "L018", "name": "Johnathan Morgan", "trade": "Mech Fitter", "is_active": true},
  {"employee_number": "AGY0115", "name": "Jon Jo Sims", "trade": "", "is_active": true},
  {"employee_number": "M689", "name": "Jordan David", "trade": "Apprentice", "is_active": true},
  {"employee_number": "AGY0116", "name": "Jordan Mortimer", "trade": "", "is_active": true},
  {"employee_number": "L664", "name": "Jordan Rogers", "trade": "", "is_active": true},
  {"employee_number": "AGY0117", "name": "Jordan Thomas", "trade": "", "is_active": true},
  {"employee_number": "L950", "name": "Joseph Chard", "trade": "", "is_active": true},
  {"employee_number": "AGY0118", "name": "Josh Coles", "trade": "Quality Eng", "is_active": true},
  {"employee_number": "M687", "name": "Josh Evans", "trade": "", "is_active": true},
  {"employee_number": "AGY0119", "name": "Josh Harris", "trade": "", "is_active": true},
  {"employee_number": "L444", "name": "Josh Mazey", "trade": "", "is_active": true},
  {"employee_number": "M658", "name": "Josh Rees", "trade": "", "is_active": true},
  {"employee_number": "M695", "name": "Josh Roderick", "trade": "", "is_active": true},
  {"employee_number": "M648", "name": "Josh Thomas", "trade": "", "is_active": true},
  {"employee_number": "AGY0120", "name": "Joshua Henney", "trade": "", "is_active": true},
  {"employee_number": "M471", "name": "Juliian Treen", "trade": "Electrician", "is_active": true},
  {"employee_number": "K920", "name": "Justin King", "trade": "Mech Fitter", "is_active": true},
  {"employee_number": "AGY0121", "name": "Justin Maliphant", "trade": "", "is_active": true},
  {"employee_number": "M352", "name": "Karl Pugh", "trade": "", "is_active": true},
  {"employee_number": "AGY0122", "name": "Keiran Mattocks", "trade": "", "is_active": true},
  {"employee_number": "M248", "name": "Keiron Rice", "trade": "", "is_active": true},
  {"employee_number": "AGY0123", "name": "Keith Williams", "trade": "Supervisor", "is_active": true},
  {"employee_number": "K883", "name": "Kelvin Williams", "trade": "", "is_active": true},
  {"employee_number": "AGY0124", "name": "Ken Young", "trade": "Fitter", "is_active": true},
  {"employee_number": "AGY0125", "name": "Kerry Murphy", "trade": "", "is_active": true},
  {"employee_number": "L701", "name": "Kevin Blanks", "trade": "", "is_active": true},
  {"employee_number": "H077", "name": "Kevin Thomas", "trade": "Welder", "is_active": true},
  {"employee_number": "J460", "name": "Kevin Wayne Thomas", "trade": "", "is_active": true},
  {"employee_number": "L015", "name": "Kim McNamara", "trade": "Mech Fitter", "is_active": true},
  {"employee_number": "M508", "name": "Kriss McNamara", "trade": "", "is_active": true},
  {"employee_number": "L868", "name": "Kurt Hargreaves", "trade": "", "is_active": true},
  {"employee_number": "AGY0126", "name": "Kyle Goodfellow", "trade": "Welder", "is_active": true},
  {"employee_number": "J594", "name": "Kyle Jones", "trade": "Rigger", "is_active": true},
  {"employee_number": "M255", "name": "Kyle Williams", "trade": "", "is_active": true},
  {"employee_number": "L347", "name": "L Mansfield", "trade": "", "is_active": true},
  {"employee_number": "AGY0127", "name": "Lee Beach", "trade": "", "is_active": true},
  {"employee_number": "AGY0128", "name": "Lee Evans", "trade": "", "is_active": true},
  {"employee_number": "AGY0129", "name": "Lee Fenton-Leath", "trade": "", "is_active": true},
  {"employee_number": "AGY0130", "name": "Lee Hastings", "trade": "", "is_active": true},
  {"employee_number": "L748", "name": "Lee James", "trade": "", "is_active": true},
  {"employee_number": "J954", "name": "Lee Mitchell", "trade": "Pipe Fitter", "is_active": true},
  {"employee_number": "K600", "name": "Lee Mitchell Jnr", "trade": "Pipe Welder", "is_active": true},
  {"employee_number": "M016", "name": "Lee Partridge", "trade": "", "is_active": true},
  {"employee_number": "M336", "name": "Lee Pritchard", "trade": "", "is_active": true},
  {"employee_number": "L880", "name": "Lee Rees", "trade": "", "is_active": true},
  {"employee_number": "AGY0131", "name": "Lee Richards", "trade": "", "is_active": true},
  {"employee_number": "L848", "name": "Lee Wiltshire", "trade": "Electrician", "is_active": true},
  {"employee_number": "L918", "name": "Leigh Coles", "trade": "", "is_active": true},
  {"employee_number": "L013", "name": "Leigh Jones", "trade": "Mech Fitter", "is_active": true},
  {"employee_number": "J473", "name": "Leighton Axworthy", "trade": "Mech Fitter", "is_active": true},
  {"employee_number": "AGY0132", "name": "Leslie John New", "trade": "", "is_active": true},
  {"employee_number": "M753", "name": "Lester Atterbury", "trade": "", "is_active": true},
  {"employee_number": "M742", "name": "Levi Burgess", "trade": "", "is_active": true},
  {"employee_number": "M079", "name": "Levi Williams", "trade": "", "is_active": true},
  {"employee_number": "AGY0133", "name": "Lewis Graham", "trade": "", "is_active": true},
  {"employee_number": "L710", "name": "Lewis Jones", "trade": "Mate", "is_active": true},
  {"employee_number": "L632", "name": "Lewis Phillips", "trade": "", "is_active": true},
  {"employee_number": "AGY0134", "name": "Lewis Wride", "trade": "", "is_active": true},
  {"employee_number": "AGY0135", "name": "Liam Aston", "trade": "Welder", "is_active": true},
  {"employee_number": "M140", "name": "Liam Brooker", "trade": "Mate", "is_active": true},
  {"employee_number": "AGY0136", "name": "Liam Diaz", "trade": "", "is_active": true},
  {"employee_number": "AGY0137", "name": "Liam Doughty", "trade": "", "is_active": true},
  {"employee_number": "AGY0138", "name": "Liam Hughes", "trade": "", "is_active": true},
  {"employee_number": "AGY0139", "name": "Liam Smith", "trade": "Welder/Fab", "is_active": true},
  {"employee_number": "AGY0140", "name": "Lloyd Williams", "trade": "", "is_active": true},
  {"employee_number": "AGY0141", "name": "Logan Richards", "trade": "", "is_active": true},
  {"employee_number": "AGY0142", "name": "Lucien Rousselle", "trade": "", "is_active": true},
  {"employee_number": "AGY0143", "name": "Luke Baker", "trade": "", "is_active": true},
  {"employee_number": "M507", "name": "Luke Cook", "trade": "", "is_active": true},
  {"employee_number": "L185", "name": "Luke Greaves", "trade": "", "is_active": true},
  {"employee_number": "AGY0145", "name": "Luke Lewis", "trade": "", "is_active": true},
  {"employee_number": "AGY0146", "name": "Luke Whittington", "trade": "", "is_active": true},
  {"employee_number": "M626", "name": "Lyn Richards", "trade": "", "is_active": true},
  {"employee_number": "AGY0147", "name": "M Johns", "trade": "Electrician", "is_active": true},
  {"employee_number": "AGY0148", "name": "M Mason", "trade": "", "is_active": true},
  {"employee_number": "L417", "name": "M Screen", "trade": "", "is_active": true},
  {"employee_number": "AGY0149", "name": "Malcom Barlow", "trade": "", "is_active": true},
  {"employee_number": "AGY0150", "name": "Manolis Nikitaras", "trade": "Fitters Mate", "is_active": true},
  {"employee_number": "L496", "name": "Marc Kappen", "trade": "", "is_active": true},
  {"employee_number": "AGY0151", "name": "Marcus Goodwood", "trade": "", "is_active": true},
  {"employee_number": "L041", "name": "Marcus Shepherd", "trade": "", "is_active": true},
  {"employee_number": "AGY0152", "name": "Mark Berry", "trade": "", "is_active": true},
  {"employee_number": "AGY0153", "name": "Mark Bevan", "trade": "", "is_active": true},
  {"employee_number": "AGY0154", "name": "Mark Blackwell", "trade": "Mech Fitter", "is_active": true},
  {"employee_number": "AGY0155", "name": "Mark Burnham", "trade": "Welder", "is_active": true},
  {"employee_number": "AGY0156", "name": "Mark Deane", "trade": "Fitter", "is_active": true},
  {"employee_number": "AGY0157", "name": "Mark Diaz", "trade": "", "is_active": true},
  {"employee_number": "M595", "name": "Mark Dougan", "trade": "", "is_active": true},
  {"employee_number": "AGY0158", "name": "Mark Gibby", "trade": "", "is_active": true},
  {"employee_number": "AGY0159", "name": "Mark Godwood", "trade": "", "is_active": true},
  {"employee_number": "K125", "name": "Mark Lee", "trade": "", "is_active": true},
  {"employee_number": "AGY0160", "name": "Mark Newman", "trade": "", "is_active": true},
  {"employee_number": "AGY0161", "name": "Mark Price", "trade": "", "is_active": true},
  {"employee_number": "M004", "name": "Mark Sullivan", "trade": "", "is_active": true},
  {"employee_number": "K911", "name": "Mark Swarts", "trade": "", "is_active": true},
  {"employee_number": "AGY0162", "name": "Martin Bennett", "trade": "", "is_active": true},
  {"employee_number": "M613", "name": "Martin Reynolds", "trade": "", "is_active": true},
  {"employee_number": "L155", "name": "Martyn Hull", "trade": "", "is_active": true},
  {"employee_number": "L480", "name": "Martyn Jones", "trade": "Electrician", "is_active": true},
  {"employee_number": "L765", "name": "Martyn Wigley", "trade": "", "is_active": true},
  {"employee_number": "AGY0163", "name": "Mathew Robb", "trade": "", "is_active": true},
  {"employee_number": "M563", "name": "Matthew Edwards", "trade": "", "is_active": true},
  {"employee_number": "AGY0165", "name": "Matthew Evans", "trade": "", "is_active": true},
  {"employee_number": "AGY0166", "name": "Matthew Ferrant", "trade": "", "is_active": true},
  {"employee_number": "M718", "name": "Matthew Isaac", "trade": "", "is_active": true},
  {"employee_number": "AGY0167", "name": "Matthew Parfitt", "trade": "", "is_active": true},
  {"employee_number": "L958", "name": "Matthew Tame", "trade": "", "is_active": true},
  {"employee_number": "AGY0168", "name": "Matthew Thomas", "trade": "", "is_active": true},
  {"employee_number": "L124", "name": "Matthew Worth", "trade": "", "is_active": true},
  {"employee_number": "AGY0169", "name": "Meirion Thomas", "trade": "", "is_active": true},
  {"employee_number": "AGY0170", "name": "Michael Capper", "trade": "", "is_active": true},
  {"employee_number": "L441", "name": "Michael Crook", "trade": "", "is_active": true},
  {"employee_number": "AGY0171", "name": "Michael Mangan", "trade": "", "is_active": true},
  {"employee_number": "AGY0172", "name": "Michael Sillitoe", "trade": "", "is_active": true},
  {"employee_number": "M430", "name": "Mike Anthony", "trade": "", "is_active": true},
  {"employee_number": "AGY0173", "name": "Mike Bolch", "trade": "", "is_active": true},
  {"employee_number": "AGY0174", "name": "Mike Davies", "trade": "", "is_active": true},
  {"employee_number": "K399", "name": "Mike Flage", "trade": "", "is_active": true},
  {"employee_number": "L644", "name": "Mike Jenkins", "trade": "Welder", "is_active": true},
  {"employee_number": "M392", "name": "Mike Leigh Tucker", "trade": "", "is_active": true},
  {"employee_number": "AGY0175", "name": "Michael Osborn", "trade": "", "is_active": true},
  {"employee_number": "H565", "name": "Mike Perrin", "trade": "", "is_active": true},
  {"employee_number": "AGY0176", "name": "Mike Raven", "trade": "", "is_active": true},
  {"employee_number": "AGY0177", "name": "Mike Silitoe", "trade": "Craftsman", "is_active": true},
  {"employee_number": "L087", "name": "Mike Smith", "trade": "", "is_active": true},
  {"employee_number": "AGY0178", "name": "Mike Stacey", "trade": "Supervisor", "is_active": true},
  {"employee_number": "AGY0179", "name": "Morgan Holtham", "trade": "", "is_active": true},
  {"employee_number": "AGY0180", "name": "Morgan Jones", "trade": "", "is_active": true},
  {"employee_number": "M769", "name": "Morgan Reed", "trade": "", "is_active": true},
  {"employee_number": "AGY0181", "name": "Morgan Rogers", "trade": "", "is_active": true},
  {"employee_number": "M672", "name": "Morgan Wright", "trade": "Electrician", "is_active": true},
  {"employee_number": "AGY0182", "name": "Morris Thomas", "trade": "", "is_active": true},
  {"employee_number": "AGY0183", "name": "Nathan Allwood", "trade": "", "is_active": true},
  {"employee_number": "AGY0184", "name": "Nathan Davies", "trade": "Welder", "is_active": true},
  {"employee_number": "AGY0185", "name": "Nathan Murphy", "trade": "App. Welder", "is_active": true},
  {"employee_number": "AGY0186", "name": "Nathan Rees", "trade": "", "is_active": true},
  {"employee_number": "M167", "name": "Nathan Sims", "trade": "", "is_active": true},
  {"employee_number": "AGY0187", "name": "Nathan Smith", "trade": "", "is_active": true},
  {"employee_number": "AGY0188", "name": "Nathan Williams", "trade": "Mate", "is_active": true},
  {"employee_number": "AGY0189", "name": "Neil Antill", "trade": "", "is_active": true},
  {"employee_number": "L136", "name": "Neil Lloyd", "trade": "", "is_active": true},
  {"employee_number": "L231", "name": "Neil Reid", "trade": "", "is_active": true},
  {"employee_number": "AGY0191", "name": "Nicholas Kehoe", "trade": "", "is_active": true},
  {"employee_number": "AGY0192", "name": "Nick Caruana", "trade": "", "is_active": true},
  {"employee_number": "AGY0193", "name": "Nick Elson", "trade": "", "is_active": true},
  {"employee_number": "M121", "name": "Nick Jukes", "trade": "", "is_active": true},
  {"employee_number": "AGY0194", "name": "Nick Levi", "trade": "", "is_active": true},
  {"employee_number": "L928", "name": "Nigel Howells", "trade": "", "is_active": true},
  {"employee_number": "AGY0195", "name": "Nigel Meyrick", "trade": "", "is_active": true},
  {"employee_number": "AGY0196", "name": "Nigel Williams", "trade": "", "is_active": true},
  {"employee_number": "J349", "name": "Olly Rowe", "trade": "", "is_active": true},
  {"employee_number": "AGY0197", "name": "Owain Pritchard", "trade": "", "is_active": true},
  {"employee_number": "AGY0198", "name": "Owen Davies", "trade": "", "is_active": true},
  {"employee_number": "K977", "name": "P Setchfield", "trade": "", "is_active": true},
  {"employee_number": "M646", "name": "Paul Allen", "trade": "", "is_active": true},
  {"employee_number": "M452", "name": "Paul Barton", "trade": "", "is_active": true},
  {"employee_number": "L096", "name": "Paul Bastian", "trade": "Pipe Fitter", "is_active": true},
  {"employee_number": "K197", "name": "Paul Carr", "trade": "Electrician", "is_active": true},
  {"employee_number": "L586", "name": "Paul Edwards", "trade": "Electrician", "is_active": true},
  {"employee_number": "AGY0199", "name": "Paul Gibbon", "trade": "", "is_active": true},
  {"employee_number": "L867", "name": "Paul Hargreaves", "trade": "", "is_active": true},
  {"employee_number": "L088", "name": "Paul Jenkins", "trade": "Mech Fitter", "is_active": true},
  {"employee_number": "AGY0200", "name": "Paul Kelly", "trade": "Stores", "is_active": true},
  {"employee_number": "AGY0201", "name": "Paul Kenyon", "trade": "", "is_active": true},
  {"employee_number": "AGY0202", "name": "Paul Lawrence", "trade": "", "is_active": true},
  {"employee_number": "K967", "name": "Paul Lonsdale", "trade": "", "is_active": true},
  {"employee_number": "AGY0203", "name": "Paul Lumihi", "trade": "", "is_active": true},
  {"employee_number": "K578", "name": "Paul Mullins", "trade": "", "is_active": true},
  {"employee_number": "J567", "name": "Paul Ryan", "trade": "Mech Fitter", "is_active": true},
  {"employee_number": "L090", "name": "Paul Stanley", "trade": "Mech Fitter", "is_active": true},
  {"employee_number": "L702", "name": "Peter Andrews", "trade": "", "is_active": true},
  {"employee_number": "AGY0204", "name": "Peter Grey", "trade": "", "is_active": true},
  {"employee_number": "M615", "name": "Peter Monks", "trade": "Rigger", "is_active": true},
  {"employee_number": "AGY0205", "name": "Phil Doherty", "trade": "", "is_active": true},
  {"employee_number": "L007", "name": "Phil Doyle", "trade": "Rigger", "is_active": true},
  {"employee_number": "AGY0206", "name": "Phil Long", "trade": "Mech Fitter", "is_active": true},
  {"employee_number": "AGY0207", "name": "Phil Mercer", "trade": "", "is_active": true},
  {"employee_number": "L066", "name": "Phil Thomas", "trade": "Mech Fitter", "is_active": true},
  {"employee_number": "J972", "name": "Phil Tobin", "trade": "", "is_active": true},
  {"employee_number": "L944", "name": "Phil Williams", "trade": "", "is_active": true},
  {"employee_number": "M122", "name": "R Harrison", "trade": "", "is_active": true},
  {"employee_number": "AGY0208", "name": "R Watkin", "trade": "Electrician", "is_active": true},
  {"employee_number": "M078", "name": "Ralph Richards", "trade": "Electrician", "is_active": true},
  {"employee_number": "AGY0209", "name": "Ray Sheldon", "trade": "", "is_active": true},
  {"employee_number": "AGY0210", "name": "Rhys Arnold", "trade": "Welder", "is_active": true},
  {"employee_number": "M133", "name": "Rhys Carney", "trade": "", "is_active": true},
  {"employee_number": "M680", "name": "Rhys Evans", "trade": "", "is_active": true},
  {"employee_number": "M196", "name": "Rhys Jones", "trade": "", "is_active": true},
  {"employee_number": "AGY0211", "name": "Rhys Reed", "trade": "", "is_active": true},
  {"employee_number": "M416", "name": "Rhys Stockdale", "trade": "", "is_active": true},
  {"employee_number": "J229", "name": "Richard Green", "trade": "", "is_active": true},
  {"employee_number": "L810", "name": "Richard Hayward", "trade": "", "is_active": true},
  {"employee_number": "AGY0212", "name": "Richard Jones", "trade": "", "is_active": true},
  {"employee_number": "AGY0213", "name": "Richard Mills", "trade": "", "is_active": true},
  {"employee_number": "M634", "name": "Richard Owen", "trade": "", "is_active": true},
  {"employee_number": "AGY0214", "name": "Richard Passmore", "trade": "Project Manager", "is_active": true},
  {"employee_number": "L781", "name": "Richard Roberts", "trade": "Electrician", "is_active": true},
  {"employee_number": "AGY0215", "name": "Richard Rowe", "trade": "", "is_active": true},
  {"employee_number": "AGY0216", "name": "Richard Smith", "trade": "", "is_active": true},
  {"employee_number": "AGY0217", "name": "Richard Williams", "trade": "", "is_active": true},
  {"employee_number": "L028", "name": "Richie Williams", "trade": "Mech Fitter", "is_active": true},
  {"employee_number": "AGY0218", "name": "Ricky Molyneux", "trade": "", "is_active": true},
  {"employee_number": "AGY0219", "name": "Ricky Spence", "trade": "", "is_active": true},
  {"employee_number": "AGY0220", "name": "Rikki Hopkins", "trade": "", "is_active": true},
  {"employee_number": "M001", "name": "Rob CAT Davies", "trade": "", "is_active": true},
  {"employee_number": "L122", "name": "Rob Francis", "trade": "", "is_active": true},
  {"employee_number": "M374", "name": "Rob James", "trade": "", "is_active": true},
  {"employee_number": "AGY0221", "name": "Rob Loughran", "trade": "", "is_active": true},
  {"employee_number": "AGY0222", "name": "Rob Morgan", "trade": "", "is_active": true},
  {"employee_number": "J339", "name": "Rob Rowe", "trade": "", "is_active": true},
  {"employee_number": "K854", "name": "Robby Griffiths", "trade": "", "is_active": true},
  {"employee_number": "M657", "name": "Robert Clark", "trade": "", "is_active": true},
  {"employee_number": "AGY0223", "name": "Robert Coles", "trade": "Welder", "is_active": true},
  {"employee_number": "L402", "name": "Robert Collins", "trade": "", "is_active": true},
  {"employee_number": "AGY0224", "name": "Robert Heywood", "trade": "", "is_active": true},
  {"employee_number": "M481", "name": "Robert L Davies", "trade": "", "is_active": true},
  {"employee_number": "AGY0225", "name": "Robert Manning", "trade": "", "is_active": true},
  {"employee_number": "M706", "name": "Robert McFarlane", "trade": "", "is_active": true},
  {"employee_number": "AGY0226", "name": "Robert Norman", "trade": "", "is_active": true},
  {"employee_number": "J158", "name": "Robert Scaplehorn", "trade": "", "is_active": true},
  {"employee_number": "AGY0227", "name": "Robin Rees", "trade": "", "is_active": true},
  {"employee_number": "L420", "name": "Rory Ferneyhough-Evans", "trade": "Fabricator Welder", "is_active": true},
  {"employee_number": "AGY0228", "name": "Rowun Rees", "trade": "", "is_active": true},
  {"employee_number": "L177", "name": "Russell Barnett", "trade": "", "is_active": true},
  {"employee_number": "AGY0229", "name": "Ryan Harris", "trade": "", "is_active": true},
  {"employee_number": "AGY0230", "name": "Ryan Phillips", "trade": "", "is_active": true},
  {"employee_number": "L976", "name": "Ryan Rees", "trade": "", "is_active": true},
  {"employee_number": "AGY0231", "name": "Ryan Shaw", "trade": "", "is_active": true},
  {"employee_number": "K966", "name": "S Finch", "trade": "", "is_active": true},
  {"employee_number": "L241", "name": "S Pollard", "trade": "", "is_active": true},
  {"employee_number": "AGY0232", "name": "S Williams", "trade": "Fabricator Welder", "is_active": true},
  {"employee_number": "AGY0233", "name": "Sam Jones", "trade": "", "is_active": true},
  {"employee_number": "AGY0234", "name": "Sam Willis", "trade": "", "is_active": true},
  {"employee_number": "AGY0235", "name": "Scott Lewis", "trade": "", "is_active": true},
  {"employee_number": "L770", "name": "Sean Adams", "trade": "Rigger", "is_active": true},
  {"employee_number": "L754", "name": "Sean Kelly", "trade": "", "is_active": true},
  {"employee_number": "AGY0236", "name": "Sean O'Neill", "trade": "", "is_active": true},
  {"employee_number": "M412", "name": "Shane Davies", "trade": "", "is_active": true},
  {"employee_number": "AGY0237", "name": "Shane Evans", "trade": "Welder", "is_active": true},
  {"employee_number": "AGY0238", "name": "Shane O'Keefe", "trade": "", "is_active": true},
  {"employee_number": "AGY0239", "name": "Shane Scannell", "trade": "Fitters Mate", "is_active": true},
  {"employee_number": "M373", "name": "Shaun Bennett", "trade": "", "is_active": true},
  {"employee_number": "M628", "name": "Shaun Thomas", "trade": "", "is_active": true},
  {"employee_number": "M597", "name": "Simon Broad", "trade": "", "is_active": true},
  {"employee_number": "AGY0240", "name": "Simon Dalling", "trade": "", "is_active": true},
  {"employee_number": "AGY0241", "name": "Simon Galagher", "trade": "", "is_active": true},
  {"employee_number": "AGY0242", "name": "Simon Jenkins", "trade": "Mech Fitter", "is_active": true},
  {"employee_number": "AGY0243", "name": "Simon Neale", "trade": "", "is_active": true},
  {"employee_number": "AGY0244", "name": "Stephen Evans", "trade": "", "is_active": true},
  {"employee_number": "H581", "name": "Stephen Jenkins", "trade": "", "is_active": true},
  {"employee_number": "AGY0245", "name": "Stephen McCollum", "trade": "", "is_active": true},
  {"employee_number": "AGY0246", "name": "Stephen O'Keefe", "trade": "", "is_active": true},
  {"employee_number": "M244", "name": "Stephen Williams", "trade": "", "is_active": true},
  {"employee_number": "AGY0247", "name": "Steve Bean", "trade": "", "is_active": true},
  {"employee_number": "AGY0248", "name": "Steve Foster", "trade": "", "is_active": true},
  {"employee_number": "L645", "name": "Steve Fowler", "trade": "", "is_active": true},
  {"employee_number": "L376", "name": "Steve Gardner", "trade": "Electrician", "is_active": true},
  {"employee_number": "K439", "name": "Steve Giles", "trade": "", "is_active": true},
  {"employee_number": "AGY0249", "name": "Steve Gilmour", "trade": "", "is_active": true},
  {"employee_number": "AGY0250", "name": "Steven Hewitson", "trade": "", "is_active": true},
  {"employee_number": "J405", "name": "Steve James", "trade": "Pipe Fitter", "is_active": true},
  {"employee_number": "AGY0251", "name": "Steve Kenny", "trade": "", "is_active": true},
  {"employee_number": "AGY0252", "name": "Steve Lane", "trade": "", "is_active": true},
  {"employee_number": "L774", "name": "Steve Mike Evans", "trade": "", "is_active": true},
  {"employee_number": "L148", "name": "Steve Oglesby", "trade": "Mech Fitter", "is_active": true},
  {"employee_number": "AGY0253", "name": "Steve Owen", "trade": "", "is_active": true},
  {"employee_number": "M499", "name": "Steve Roberts", "trade": "", "is_active": true},
  {"employee_number": "K880", "name": "Steve Rowbottom", "trade": "", "is_active": true},
  {"employee_number": "K043", "name": "Steve Williams", "trade": "Mech Fitter", "is_active": true},
  {"employee_number": "K572", "name": "Steve Williams", "trade": "Welder", "is_active": true},
  {"employee_number": "AGY0254", "name": "Steven Watkins", "trade": "", "is_active": true},
  {"employee_number": "AGY0255", "name": "Stewart Straw", "trade": "", "is_active": true},
  {"employee_number": "AGY0256", "name": "Stuart Baugh", "trade": "", "is_active": true},
  {"employee_number": "K466", "name": "Stuart Rees", "trade": "Mech Fitter", "is_active": true},
  {"employee_number": "L208", "name": "T Mark Sprake", "trade": "Mech Fitter", "is_active": true},
  {"employee_number": "AGY0257", "name": "Terence John Gormon", "trade": "Fitter", "is_active": true},
  {"employee_number": "AGY0258", "name": "Terry Morris", "trade": "", "is_active": true},
  {"employee_number": "J815", "name": "Terry Power", "trade": "Pipe Fitter", "is_active": true},
  {"employee_number": "M599", "name": "Thomas Ashford", "trade": "", "is_active": true},
  {"employee_number": "M312", "name": "Tim Jones", "trade": "Rigger", "is_active": true},
  {"employee_number": "AGY0259", "name": "Tim Weaving", "trade": "", "is_active": true},
  {"employee_number": "AGY0260", "name": "Tobias Ford", "trade": "", "is_active": true},
  {"employee_number": "AGY0261", "name": "Tobias Lance", "trade": "", "is_active": true},
  {"employee_number": "AGY0262", "name": "Toby Lodge", "trade": "", "is_active": true},
  {"employee_number": "L804", "name": "Tom Axenderrie", "trade": "", "is_active": true},
  {"employee_number": "L463", "name": "Tom Boyd", "trade": "Electrician", "is_active": true},
  {"employee_number": "L563", "name": "Tom Jenkins", "trade": "Electrician", "is_active": true},
  {"employee_number": "M692", "name": "Tomas Cole", "trade": "", "is_active": true},
  {"employee_number": "AGY0263", "name": "Tomas Price", "trade": "", "is_active": true},
  {"employee_number": "J159", "name": "Tony Wargent", "trade": "Rigger", "is_active": true},
  {"employee_number": "AGY0264", "name": "Vincent Gee", "trade": "", "is_active": true},
  {"employee_number": "AGY0265", "name": "Viv Williams", "trade": "", "is_active": true},
  {"employee_number": "K490", "name": "Warren Owens", "trade": "Mech Fitter", "is_active": true},
  {"employee_number": "AGY0266", "name": "Wayne Adams", "trade": "", "is_active": true},
  {"employee_number": "L051", "name": "Wayne Brooks", "trade": "Mech Fitter", "is_active": true},
  {"employee_number": "M598", "name": "Wayne Cassar", "trade": "", "is_active": true},
  {"employee_number": "AGY0267", "name": "Wayne Murphy", "trade": "", "is_active": true},
  {"employee_number": "AGY0268", "name": "Steven Stickler", "trade": "", "is_active": true},
  {"employee_number": "AGY0269", "name": "Lewis Coles", "trade": "", "is_active": true},
  {"employee_number": "AGY0270", "name": "Sam Diaz", "trade": "", "is_active": true},
  {"employee_number": "AGY0271", "name": "Jordan Piontecki", "trade": "", "is_active": true},
  {"employee_number": "AGY0272", "name": "Phillip Keith Williams", "trade": "Supervisor", "is_active": true}
];
