// ═══════════════════════════════════════════════════════════
// MII RAMS Builder - Environment Library
// Generated from desktop RAMSBuilder environment_library.json
// ═══════════════════════════════════════════════════════════

const ENVIRONMENT_LIBRARY = {
  title: "19. Environmental Risk Assessment",
  description: "Consider the work/tasks to be undertaken and how this may impact on the environment. Identify controls to mitigate these impacts.",
  questions: [
    {
      id: "waste",
      question: "Will the project generate waste?",
      full_question: "Will the project generate waste? If yes, then how is the waste to be disposed of?",
      default_answer: "NO",
      default_mechanisms: [
        "Consumable bolts, nuts & gaskets",
        "Filters and filter media",
        "Scrap metal and offcuts",
        "Packaging materials",
        "Used PPE",
        "General site waste"
      ],
      default_controls: [
        "Remove to designated recycle compound",
        "Segregate waste by type (metal, general, hazardous)",
        "Use licensed waste carrier for disposal",
        "Maintain waste transfer notes",
        "Dispose of hazardous waste via approved contractor",
        "Skip or waste bins provided on site"
      ]
    },
    {
      id: "diesel_oil",
      question: "Is diesel / oil / grease being brought on site?",
      full_question: "Is diesel / oil / grease being brought on site? If yes, indicate how it will be stored.",
      default_answer: "NO",
      default_mechanisms: [
        "Diesel for generators/equipment",
        "Hydraulic oil for machinery",
        "Lubricating oil and grease",
        "Fuel for vehicles"
      ],
      default_controls: [
        "Store in bunded area (110% capacity)",
        "Use drip trays under equipment",
        "Keep spill kit available on site",
        "Secure storage when not in use",
        "Regular inspection of containers for leaks",
        "No refuelling within 10m of drains"
      ]
    },
    {
      id: "chemicals",
      question: "Are chemicals and other harmful materials being used?",
      full_question: "Are chemicals and other harmful materials being used during the project? If yes, identify what and indicate how they are being stored.",
      default_answer: "NO",
      default_mechanisms: [
        "Cleaning chemicals",
        "Paints and solvents",
        "Adhesives and sealants",
        "Welding consumables",
        "Cutting fluids"
      ],
      default_controls: [
        "Store in designated chemical storage area",
        "Keep COSHH data sheets on site",
        "Use only as per manufacturer's instructions",
        "Ensure adequate ventilation",
        "Wear appropriate PPE as per COSHH assessment",
        "Dispose of empty containers correctly"
      ]
    },
    {
      id: "emissions",
      question: "Will the project create any emissions (dust or fume)?",
      full_question: "Will the project create any emissions (dust or fume) to the atmosphere? If yes, what and how?",
      default_answer: "NO",
      default_mechanisms: [
        "Grinding and cutting operations",
        "Welding fumes",
        "Exhaust from generators/vehicles",
        "Dust from demolition work",
        "Spray painting"
      ],
      default_controls: [
        "Use LEV (Local Exhaust Ventilation) where possible",
        "Dampen down dusty materials",
        "Use appropriate RPE (FFP3 minimum for fumes)",
        "Screen work area to contain dust",
        "Maintain equipment to reduce emissions",
        "Work in well-ventilated areas"
      ]
    },
    {
      id: "effluent",
      question: "Will the project create any effluent?",
      full_question: "Will the project create any effluent? If yes, what effluent will this be and how will it be dealt with?",
      default_answer: "NO",
      default_mechanisms: [
        "Washdown water",
        "Contaminated water from equipment",
        "Water from pressure washing",
        "Coolant from cutting operations"
      ],
      default_controls: [
        "Contain all effluent - do not allow to enter drains",
        "Use drip trays and bunding",
        "Dispose via licensed waste carrier",
        "Use absorbent materials for spills",
        "Prevent contaminated water reaching watercourses",
        "Use settlement tanks if required"
      ]
    },
    {
      id: "noise",
      question: "Is there potential for noise to be generated?",
      full_question: "Is there a potential for noise to be generated by the project? If yes, what will be done to mitigate?",
      default_answer: "NO",
      default_mechanisms: [
        "Power tools (grinders, drills)",
        "Impact tools (hammers, chisels)",
        "Generators and compressors",
        "Vehicles and plant",
        "General construction noise"
      ],
      default_controls: [
        "Provide hearing protection (PPE)",
        "Restrict noisy work to agreed hours",
        "Use silenced equipment where possible",
        "Erect noise barriers if required",
        "Notify neighbours of noisy work periods",
        "Carry out noise assessment if required"
      ]
    },
    {
      id: "light",
      question: "Is there potential for light to become a nuisance?",
      full_question: "Is there a potential for light to become a nuisance? If so how will this be controlled?",
      default_answer: "NO",
      default_mechanisms: [
        "Temporary lighting for night work",
        "Task lighting",
        "Security lighting",
        "Welding arc light"
      ],
      default_controls: [
        "Direct lights away from neighbouring properties",
        "Use shielded lighting fixtures",
        "Switch off lights when not required",
        "Screen welding operations",
        "Restrict lit work to agreed hours",
        "Use minimum lighting necessary for safe working"
      ]
    },
    {
      id: "smoke_fume_odour",
      question: "Is there potential to create smoke, fume or odour?",
      full_question: "Is there potential for the project to create smoke, fume or odour? If yes, how will this be controlled?",
      default_answer: "NO",
      default_mechanisms: [
        "Hot work (welding, cutting, brazing)",
        "Painting and coating operations",
        "Adhesives and sealants",
        "Engine exhausts",
        "Burning of waste (prohibited)"
      ],
      default_controls: [
        "Ensure adequate ventilation",
        "Use fume extraction equipment",
        "Notify neighbours if significant odour expected",
        "No burning of materials on site",
        "Use water-based products where possible",
        "Work in open air where practicable"
      ]
    },
    {
      id: "other_environmental",
      question: "Are there other environmental considerations?",
      full_question: "Are there other environmental considerations that will need to be taken into account? If yes, provide details.",
      default_answer: "NO",
      default_mechanisms: [
        "Proximity to watercourses",
        "Protected wildlife/habitats",
        "Archaeological considerations",
        "Proximity to residential areas",
        "Access routes and traffic",
        "Ground contamination potential"
      ],
      default_controls: [
        "Consult with client environmental team",
        "Implement environmental management plan",
        "Report any environmental incidents immediately",
        "Follow site-specific environmental procedures",
        "Protect sensitive areas as identified",
        "Minimise disturbance to local area"
      ]
    }
  ]
};
