const MII_HAZARDS = [
  {
    "id": "dbb9b087-96aa-52bc-b0fe-7dd7ec323e17",
    "name": "Airborne Dust",
    "category": "Chemical & Hazardous Substances",
    "risk_description": "Inhalation of dust particles, dust particles becoming lodged in eyes",
    "who_harmed": "Working Party and others",
    "default_controls": "Ensure that suitable PPE and RPE is selected based on the level of risk and amount of dust in area e.g. Spoggles in areas of high dust levels. Ensure your aware of the location of your nearest eye wash station.",
    "initial_likelihood": 4,
    "initial_severity": 3,
    "final_likelihood": 1,
    "final_severity": 3
  },
  {
    "id": "632f630e-29e3-52f2-8b7f-b772ecbb5ea7",
    "name": "Asbestos",
    "category": "Chemical & Hazardous Substances",
    "risk_description": "Fatal diseases - Asbestosis, lung cancer, mesothelioma",
    "who_harmed": "Working Party and others",
    "default_controls": "It is the site owner’s responsibility to communicate the location of any asbestos that may affect the working party. Through access to asbestos registers and the relevant permits, your manager/ supervisor must be made aware of the location of any asbestos in the work area and pass the information on to the working party. Always take note of any signs or labels communicating the presence of asbestos however, never assume the location of all asbestos is known, treat any materials that could be asbestos as asbestos until proven otherwise. Contact your supervisor with any concerns, Asbestos awareness training is available via MII's E-Learning Portal.  If you believe you may disturb asbestos during your work, stop work and inform your supervisor immediately, the work method will have to be amended accordingly. You must report any damage or deterioration of asbestos containing materials and report any near misses or concerns. If you believe you may have been exposed to airborne fibres contact your supervisor immediately.",
    "initial_likelihood": 4,
    "initial_severity": 5,
    "final_likelihood": 1,
    "final_severity": 5
  },
  {
    "id": "549784c8-7d30-5610-a5e0-b3a8f66a1677",
    "name": "Diesel Fumes",
    "category": "Chemical & Hazardous Substances",
    "risk_description": "Health issues caused by Inhalation of hazardous fumes",
    "who_harmed": "Working Party and others",
    "default_controls": "Ensure any fume generating equipment is used in a well ventilated area or in conjunction with any Local Exhaust Ventilation systems where possible. Turn off any fume generating equipment when it is not in use and use the appropriate RPE where exposure is unavoidable. Ensure all equipment used is in good condition and not exuding excess fumes, report any obvious defects to your supervisor immediately.",
    "initial_likelihood": 4,
    "initial_severity": 4,
    "final_likelihood": 1,
    "final_severity": 4
  },
  {
    "id": "e08b5e46-5278-5dc8-be0f-49c67c5a88d0",
    "name": "Hazardous Process Gasses",
    "category": "Chemical & Hazardous Substances",
    "risk_description": "Death, disease and ill health",
    "who_harmed": "Working Party",
    "default_controls": "All personnel working in a gas hazard area must be gas awareness trained and carry a personal gas monitor with them at all times. Always ensure you have sufficient battery life on your gas monitor for the amount of time you'll be working in a gas hazard area. If your gas alarm sounds always move away from the area immediately to fresh air and report the incident to your supervisor. Respond to any local fixed gas alarm systems in-line with site/local emergency procedures.  In the event of a wider gas emergency immediately proceed  to your nearest gas safe haven.",
    "initial_likelihood": 4,
    "initial_severity": 5,
    "final_likelihood": 1,
    "final_severity": 5
  },
  {
    "id": "c2c0ff30-7484-55b0-bd59-c8246abfa5f4",
    "name": "Hazardous Substances Fuels, Paints, Lubrications etc.",
    "category": "Chemical & Hazardous Substances",
    "risk_description": "Injuries and diseases due to - Inhalation of hazardous fumes, contact with irritants, contact with hazardous substances etc.",
    "who_harmed": "Working party",
    "default_controls": "Ensure all Material Safety Data Sheets are available to employees and ensure all advice and controls stated on the MSDS are implemented such as storage and handling etc. Maintain good personal hygiene at all times, e.g. wash your hands on a regular basis. Ensure work areas are cleared of hazardous substances so far as practicable prior to commencing work in the area. Wear suitable PPE to protect any part of the body that may come into contact with the substance - Chemical resistant gloves, overalls/ suits, goggles etc.  Wear suitable RPE to protect against hazardous fumes and mists.",
    "initial_likelihood": 4,
    "initial_severity": 4,
    "final_likelihood": 1,
    "final_severity": 4
  },
  {
    "id": "eda7a318-ae4d-53ce-85d4-8a0b6b200249",
    "name": "Lead",
    "category": "Chemical & Hazardous Substances",
    "risk_description": "Ill health due to Lead Poisoning",
    "who_harmed": "Working Party",
    "default_controls": "Ensure the correct PPE and RPE is worn when required. Practise good hygiene at all times by washing exposed areas of skin immediately on leaving the work area, and prior to smoking, eating or drinking; never smoke, eat or drink within work area. Report any of the following symptoms if they occur whilst working with lead. Headaches, Tiredness, Irritability, Constipation, Nausea, Stomach Pains, Anaemia, Weight Loss.",
    "initial_likelihood": 4,
    "initial_severity": 4,
    "final_likelihood": 1,
    "final_severity": 4
  },
  {
    "id": "09807958-8014-5b48-a7c7-6af33dd26245",
    "name": "Oxygen",
    "category": "Chemical & Hazardous Substances",
    "risk_description": "Serious and fatal injuries due to oxygen enriched atmospheres, potential explosions, increased risk of fire and burns",
    "who_harmed": "Working Party and others",
    "default_controls": "Handle oxygen cylinders carefully. Use a purpose built trolley to move them; Keep cylinders chained or clamped to prevent them from falling over; Store oxygen cylinders when not in use in a well-ventilated storage area, away from combustible materials and separated from cylinders of flammable gas. With regard to oxygen equipment, you should always: Open the valve slowly. Ensure that the pressure adjusting screw of the pressure regulator is fully unwound, so that the regulator outlet valve is closed before opening the oxygen cylinder valve, particularly when opening the cylinder valve for the first time after changing cylinders; Ensure that cylinder valves are closed and piped supplies isolated whenever work is stopped. Do not try to cut off the supply of oxygen by nipping or kinking flexible hose when changing equipment, e.g. blowpipes; Maintain hoses and other equipment in good condition. Leak tests can be carried out easily using a proprietary spray or liquid solution that is certified for use on oxygen systems. Soap or liquids that may contain grease should not be used. Always keep oxygen equipment clean, use clean hands or gloves when assembling oxygen equipment and wear suitable clean clothing free from oil and combustible contaminants. If there is risk of creating an oxygen enriched environment i.e. inside a confined space, or in a poorly ventilated area then additional control measures must be in place such as, personal gas monitors, mechanical ventilation, atmospheric testing etc.",
    "initial_likelihood": 4,
    "initial_severity": 5,
    "final_likelihood": 2,
    "final_severity": 5
  },
  {
    "id": "624a9905-0958-5f47-98eb-1bec21204fa3",
    "name": "Process Acids",
    "category": "Chemical & Hazardous Substances",
    "risk_description": "Injury and disease due to contact with corrosive Acidic substance, skin burns, irritation etc.",
    "who_harmed": "Working Party and Others",
    "default_controls": "Ensure all relevant isolations are in place and all systems containing process acids / fumes have been drained and or flushed prior to starting work. Ensure that suitable PPE And RPE is selected based off the level of risk. Ensure skin is covered where it could otherwise come into contact with process acids. Good levels of hygiene must be maintained, ensure you wash your hands before eating and at the end of every shift. If you should start to feel any irritation on your skin or start to feel unwell speak to your supervisor immediately. Ensure tools used in an area where they could come into contact with process acids are cleaned thoroughly at the end of the task.",
    "initial_likelihood": 4,
    "initial_severity": 4,
    "final_likelihood": 1,
    "final_severity": 4
  },
  {
    "id": "3e735799-f6f4-5509-8688-ecc0186313f3",
    "name": "Confined Spaces",
    "category": "Confined Space",
    "risk_description": "Serious and fatal injuries due to - Explosive and hazardous atmospheres, collapse of structure, extreme temperatures, flooding,",
    "who_harmed": "Working Party",
    "default_controls": "Before confined space work can begin the following must be in place: \n1. A competent supervisor to control operations\n2. Ensure all personnel are suitable to confined space working, and are trained to work in confined spaces.\n3. Ensure all necessary isolations are in place and a permit to work is obtained where necessary. \n4. Ensure the CS is purged and cleaned when required. \n5. Ensure the entrance is big enough to allow for any additional PPE and equipment and is kept clear at all times. \n6. Increase ventilation where possible either mechanically or through opening additional hatches. \n7. Ensure an atmosphere test or continuous air monitoring is in place prior to entering a confined space. Personal gas monitors should be worn at all times in a confined space or around an open entrance. \n8. Non-sparking tools and specialist lighting are essential where flammable or explosive atmospheres are likely. \n9. BA equipment must be worn if the air inside the space cannot be made fit to breathe. \n10. Ensure you have read and understood a rescue plan. This should include all arrangements in the event of an emergency such as roles of appointed persons, rescue equipment, notifying local emergency services etc.",
    "initial_likelihood": 5,
    "initial_severity": 5,
    "final_likelihood": 2,
    "final_severity": 5
  },
  {
    "id": "1b8efb67-2d81-5aee-9b55-4a6c7c043e02",
    "name": "110v Drills & Magnetic Base Drills",
    "category": "Electrical",
    "risk_description": "Injuries caused by rotating equipment / missing safety features",
    "who_harmed": "Working Party and others",
    "default_controls": "Carry out a pre-use inspection prior to use of equipment. Ensure all safety features are present including drill handles, guards & safety chains (for magnetic base drills). Magnetic drills should always have a power source when being used and that the safety chain must always be fixed to a suitable anchor point, if using multiple extension leads the joints should be marked with warning signs to make others aware of mag drill in use. Ensure the correct PPE is worn for the task, wearing loose clothing and gloves should be avoided when using rotating equipment. The correct size and type of drill bit should always be used for the task and where possible, the work piece should be suitably secured prior to drilling.  Be aware of the drill \"kicking\" if the drill bit becomes jammed during operation, always operate the drill using both hands, cutting paste should be used where practicable.",
    "initial_likelihood": 4,
    "initial_severity": 4,
    "final_likelihood": 1,
    "final_severity": 4
  },
  {
    "id": "fb0747c6-e8b0-5187-911c-b32fecb63ebd",
    "name": "Electrical Power",
    "category": "Electrical",
    "risk_description": "Serious or fatal injuries caused by electric shock resulting in burns, damage to muscle tissue etc, crushing and entrapment injuries caused by electrically operated plant and equipment",
    "who_harmed": "Working Party and others",
    "default_controls": "Never carry out work on live plant or machinery. Ensure that suitable isolation controls are put in place prior to carrying out any works on electrical equipment. Raise any concerns with your supervisor. The supervisor will inform you when he is going to cancel the isolations, and from that moment on you must not return to that work area for any reason. Raise any concerns with your supervisor immediately. All electrical cables must be treated as live unless proven otherwise.",
    "initial_likelihood": 5,
    "initial_severity": 5,
    "final_likelihood": 1,
    "final_severity": 5
  },
  {
    "id": "7a4ff80b-07ed-5d0d-8188-aea332e917df",
    "name": "Overhead Power",
    "category": "Electrical",
    "risk_description": "Serious or fatal injuries caused by electric shock resulting in burns, damage to muscle tissue etc",
    "who_harmed": "Working Party",
    "default_controls": "Always be aware of the potential of overhead power cables when working outside, particularly if working in or around sub-stations or transformer pens. Only trained and competent personnel to work within the confines of High Voltage areas. Consider whether your work requires a crane standing order.",
    "initial_likelihood": 4,
    "initial_severity": 5,
    "final_likelihood": 1,
    "final_severity": 5
  },
  {
    "id": "2411b344-70ab-523f-a528-4b2c00988786",
    "name": "Portable Electrical Equipment",
    "category": "Electrical",
    "risk_description": "Serious and fatal injuries due to - Electrocution, burns",
    "who_harmed": "Working Party",
    "default_controls": "All portable electrical equipment MUST hold a current and in-date PAT Tag and all guarding and safety features must be in place. If the tool your are provided is out of compliance then return it to the stores and request a compliant tool. Carry out a pre-use inspection of the equipment, check for: \n•Damage to the cable sheath;\n•Damage to the plug, e.g. the casing is cracking, the pins are bent or signs of overheating;     \n•Inadequate joints, including taped joints in the cable;\n•The outer sheath of the cable not being effectively secured where it enters the plug or the equipment. Obvious evidence would be if the coloured insulation of the internal cable cores were showing;\n•The equipment being subjected to conditions for     which it is not suitable, e.g. it is wet or excessively contaminated;\n•Damage to the external casing of the equipment or there are some loose parts or screws; and\n•Overheating - Burn marks or discoloration.\nAlways report faulty equipment. Do not attempt to carry out repairs unless you are authorised to do so. Use battery operated equipment where possible, all site equipment must be 110v.",
    "initial_likelihood": 5,
    "initial_severity": 5,
    "final_likelihood": 1,
    "final_severity": 5
  },
  {
    "id": "22e85af7-947a-5825-a414-abd9db6fab59",
    "name": "Extreme Temperatures",
    "category": "Environmental",
    "risk_description": "Heat stress, physiological well-being, dehydration",
    "who_harmed": "Working Party",
    "default_controls": "Personnel should be able to recognise the symptoms of heat stress: An inability to concentrate, muscle cramps, heat rash, Severe thirst (late symptom of heat stress), fainting, heat exhaustion (fatigue, giddiness, nausea, headache, moist skin) heat stroke (hot dry skin, confusion, convulsions and eventual loss of consciousness. If you or anyone in your working party experience any of these symptoms they should contact their supervisor immediately. Ensure your are acclimatised to the conditions, gradual exposure to heat levels and to the work along with lighter duties to those unused to working in high heat conditions. Drink small amounts of water on a regular basis but avoid high caffeinated drinks such as tea and coffee. Avoid eating hot and heavy meals and take regular rest breaks in a cool well ventilated area. Try to limit work activates during the hottest part of the day/shift and give your body time to cool down before re-entering the area. Remember that your physical condition can reduce your ability to deal with the heat. Age, weight,\nfitness, health conditions (heart disease or high blood pressure), recent illness, or medications can all\naffect your ability to withstand high temperatures. If you have any concerns, please raise these with\nyour supervisor",
    "initial_likelihood": 3,
    "initial_severity": 4,
    "final_likelihood": 1,
    "final_severity": 4
  },
  {
    "id": "a2e82922-e1c9-592c-b1ed-26929f17b914",
    "name": "Hand-arm Vibration",
    "category": "Environmental",
    "risk_description": "Over-exposure can lead to long-term & irreversible health conditions such as Hand-Arm Vibration Syndrome, Vibration White Finger, Carpel Tunnel syndrome",
    "who_harmed": "Working Party",
    "default_controls": "Exposure to vibration must be monitored and recorded by employees on an ongoing basis.  Any employees who exceed the daily (in 8 hours) Action value (2.5 m/s²/ 100 points) are fully aware of the health risks and controls to minimise them.  The daily Limit Value (5 m/s² / 400 points) must never be exceeded.  Plan the task so that it is broken up with other activities and rotate the task amongst several employees to minimise exposure.",
    "initial_likelihood": 5,
    "initial_severity": 4,
    "final_likelihood": 1,
    "final_severity": 4
  },
  {
    "id": "bc001b8d-a49f-5fbb-9c99-f7f531a989d7",
    "name": "Hazardous Noise Levels",
    "category": "Environmental",
    "risk_description": "Temporary threshold shift, permanent threshold shift, tinnitus",
    "who_harmed": "Working Party and others",
    "default_controls": "If high levels of noise exist in your work area then take steps to reduce your exposure. Assess whether the work can be carried out elsewhere or if the source of noise can be isolated completely. Always wear hearing protection in areas classed as noise-hazard zones.  Adhere to awareness signs and site rules.  Hearing protection must always be worn during activities with the potential to create hazardous noise levels - When close to the use of angle grinders, impact guns, noisy mobile plant etc.",
    "initial_likelihood": 4,
    "initial_severity": 4,
    "final_likelihood": 1,
    "final_severity": 4
  },
  {
    "id": "b9f5ccf0-8d94-5dab-9863-26816a815b25",
    "name": "Inclement Weather",
    "category": "Environmental",
    "risk_description": "Flying objects, collapse/overturning of mobile plant and structures due to high winds, illness due to exposure",
    "who_harmed": "Working Party",
    "default_controls": "Do not perform lifting operations during periods of unsuitable weather conditions. Ensure any susceptible structures (Erections, structures, temporary workshops/ coverings, work pieces, tower scaffolds etc.) under our control are secured against unsuitable weather conditions. Ensure suitable weather resistant PPE is worn when required (wet weather gear/thermal clothing etc). Protect skin against excessive UV exposure (sunscreen). If weather conditions adversely effect workplace (ground conditions etc) contact your supervisor immediately.",
    "initial_likelihood": 4,
    "initial_severity": 3,
    "final_likelihood": 1,
    "final_severity": 3
  },
  {
    "id": "e7278113-374d-5adc-974f-a43acd59c491",
    "name": "Leaks, drips and spillages (Environmental hazard)",
    "category": "Environmental",
    "risk_description": "Damage to the environment, risk of slips, trips, falls",
    "who_harmed": "Working Party and others, the environment",
    "default_controls": "Report all leaks and drips to your supervisor or client immediately.    When transferring substances between containers or into plant items, ensure that suitable funnels, hoses or pump equipment are being used - Where the risk of drips or spillage remain, position drip trays at the appropriate positions.  Carry a suitable spill kit at all times or familiarise all members of the working party with the location of the nearest spill kits.  Dispose of any used spill kit components as hazardous waste.",
    "initial_likelihood": 4,
    "initial_severity": 4,
    "final_likelihood": 1,
    "final_severity": 4
  },
  {
    "id": "8be9c26b-7d80-5e3f-ab69-f623696e82cc",
    "name": "Poor Lighting",
    "category": "Environmental",
    "risk_description": "Increased chance of slips trips and falls, eye strain from poor lighting",
    "who_harmed": "Working Party and others",
    "default_controls": "Ensure adequate levels of lighting are provided before commencing any work. If the area is poorly lit then use task lighting, preferably battery operated to avoid trailing leads. If you feel that light is becoming a nuisance raise your concerns with your supervisor.",
    "initial_likelihood": 5,
    "initial_severity": 4,
    "final_likelihood": 1,
    "final_severity": 4
  },
  {
    "id": "ec5aab47-1c68-5144-a7fd-ca53b79093bc",
    "name": "Radiation",
    "category": "Environmental",
    "risk_description": "Injuries and health conditions relating to radiation exposure.",
    "who_harmed": "Working Party and Others",
    "default_controls": "Do not approach any radiation sources or enter any specified areas.  Strictly obey any signs prohibiting access into areas.",
    "initial_likelihood": 3,
    "initial_severity": 5,
    "final_likelihood": 1,
    "final_severity": 5
  },
  {
    "id": "95197197-d241-5f52-9c8a-616eed8ce87f",
    "name": "Excavations",
    "category": "Excavation",
    "risk_description": "Injuries due to falls from height and objects falling from above.",
    "who_harmed": "Working Party",
    "default_controls": "Ensure that edge protection is in place for any excavations in your work area, raise any concerns with your supervisor. If required to work in excavations ensure the correct access and egress routes are used. Ensure the correct PPE is worn at all times. Ensure nobody is effected by your work activities either above or below you.",
    "initial_likelihood": 5,
    "initial_severity": 5,
    "final_likelihood": 1,
    "final_severity": 5
  },
  {
    "id": "54482b64-f252-5b18-8ac2-0c99ee189625",
    "name": "Hot Work",
    "category": "Fire & Hot Work",
    "risk_description": "Injuries due to - Burns, Molten Metal, Ultra-violet Light, Fumes, Fire, Hot Surfaces, Potential explosion due to equipment",
    "who_harmed": "Working party and others",
    "default_controls": "A Hot-Work Certificate and/or assessment must be in place prior to carrying out hot work. Ensure the area is inspected prior to hot works taking place, remove all combustible materials, protect any vulnerable equipment from damage with the use of appropriate fire blankets, if necessary douse the area prior to starting hot works. Fume created from any hot-work activity is hazardous and suitable RPE must be used.  \n\nEnsure the below are in place: \n\n•\tCompetent Fire Watch on all appropriate levels, fire watch must stay for 1 hour after hot works have finished\n•\tMeans of Extinguishing\n•\tScreens as required\n•\tAppropriate PPE & RPE",
    "initial_likelihood": 5,
    "initial_severity": 4,
    "final_likelihood": 2,
    "final_severity": 4
  },
  {
    "id": "0b57f6c1-4fe3-5493-9a0e-aee18da45524",
    "name": "Molten Metal",
    "category": "Fire & Hot Work",
    "risk_description": "Severe Burns, eye injury, life changing injury’s, fatality",
    "who_harmed": "Working Party and others",
    "default_controls": "Molten Metal PPE must always be worn. Extreme caution must be taken when entering areas where molten metal is part of the process, only enter areas where you are authorised to enter, and pay attention to traffic light systems that forbid you to enter areas when certain activities are being undertaken",
    "initial_likelihood": 3,
    "initial_severity": 5,
    "final_likelihood": 1,
    "final_severity": 5
  },
  {
    "id": "a334fb93-836b-553f-a29a-75a2cb9abd62",
    "name": "Refuelling / Using Plant and Equipment",
    "category": "Fire & Hot Work",
    "risk_description": "Fire, Explosion, Spillage",
    "who_harmed": "Working Party and Others",
    "default_controls": "Ensure all plant and equipment is in good condition before use. Quarantine if not. Ensure plant and equipment is in a safe location. Ensure equipment is switched off prior to refuelling. Fire extinguisher to be readily available. Fuel to be stored in metal jerry can, remote from areas of hot works and clearly identifiable. Drip tray to be placed beneath any fill up points. Spill kit to be readily accessible.",
    "initial_likelihood": 4,
    "initial_severity": 4,
    "final_likelihood": 1,
    "final_severity": 4
  },
  {
    "id": "9f521322-921a-5c7a-9c16-61bca3af9e99",
    "name": "Air Arcing gouging / Lancing",
    "category": "Machinery & Equipment",
    "risk_description": "Burn Injuries, inhalation of potentially hazardous fumes, eye injuries",
    "who_harmed": "Working Party and others",
    "default_controls": "No Air Arc Gouging / Lancing to be carried out unless your supervisor / Manager has deemed you competent to do so, and you have read and understood WI (AO1) Air Carbon Arc Gouging (Lancing) if unsure raise your concerns with your supervisor / manager. Consider whether other lower risk methods are viable to carry out the work. All equipment must be inspected prior to use, do not use damaged equipment. Inspect the area to ensure it is free from any potential hazards, all combustible materials must be removed from the area and suitable screens must be erected. All persons not involved with the work activity must leave the area. Ensure the correct PPE & RPE is being worn FFP3 is the Minimum standard (change regularly based on level of exposure), if you are unsure raise concerns with your supervisor. Local Exhaust Ventilation should be considered particularly in smaller enclosed areas.",
    "initial_likelihood": 4,
    "initial_severity": 4,
    "final_likelihood": 2,
    "final_severity": 4
  },
  {
    "id": "3076b44a-2495-50c0-ad7c-3ef6ad2f4e14",
    "name": "Angle Grinders",
    "category": "Machinery & Equipment",
    "risk_description": "Injuries due to faulty or incorrect use of angle grinder - Cuts and abrasions, pinches, puncture wounds",
    "who_harmed": "Working Party",
    "default_controls": "All employees who use angle grinders must be competent to do so. Carry out a pre-use inspection of the grinder and ensure all safety features (guards, handles etc) are in place and used during operation. The correct size grinder and the correct type of disc must always be used for the task and only competent people are permitted to change the disc. Where practicable, suitably secure the work piece before work commences. Select the correct PPE for the task and always hold the angle grinder with both hands during it's operation. All 110v angle grinders must hold an in-date PAT tag. Never stand in the ‘line of fire’ of potentially ejected objects.",
    "initial_likelihood": 4,
    "initial_severity": 4,
    "final_likelihood": 2,
    "final_severity": 4
  },
  {
    "id": "74044bca-2d9a-5656-b01b-aabe3d0b9ce1",
    "name": "Compressed Gas Cylinders",
    "category": "Machinery & Equipment",
    "risk_description": "Injuries due to explosions and fire, burns etc",
    "who_harmed": "Working Party and others",
    "default_controls": "Inspect gas cylinder prior to use to ensure they are good condition. Inspect all associated equipment (regulators, hoses etc) and confirm they are in good condition and are suitable for the associated pressures. Ensure all are fitted with flashback arrestors and ensure all cylinders are secured in an upright position when in use. When not in use, return cylinders to designated storage area, fuel and oxygen cylinders should never be stored together and empty and full cylinders should be separated. Do not drop, roll or drag gas cylinders. Close the cylinder valve and replace dust caps, where provided, when a gas cylinder is not in use. Ensure that gas cylinders are positioned in a well ventilated area when in use, never use a gas cylinder in confined spaces.",
    "initial_likelihood": 5,
    "initial_severity": 4,
    "final_likelihood": 2,
    "final_severity": 4
  },
  {
    "id": "c39e0f15-6de0-59d9-a98b-09ddcb31727d",
    "name": "Cranes (Mobile, Overhead Etc)",
    "category": "Machinery & Equipment",
    "risk_description": "Injuries resulting from crane collapse or overturning, contact with suspended load etc",
    "who_harmed": "Working Party and others",
    "default_controls": "Always be mindful of cranes operating in your work area. All cranes must be subject to a thorough examination and a regular maintenance programme. Complete pre-use inspection checklists where required. Ensure the crane operator is trained and competent and ensure all crane movements are controlled by a competent banksman. Ensure that loads are never transported over populated areas, use suitable mass notification devices e.g. air horns, to warn people in the area of a crane operation. Never walk under suspended loads, remove non-essential personnel from the area and use a safety person or barriers/warning signs where required.",
    "initial_likelihood": 5,
    "initial_severity": 5,
    "final_likelihood": 2,
    "final_severity": 5
  },
  {
    "id": "46f974a0-9067-5620-8816-cf63bb5b7287",
    "name": "Failure / Collapse of Temporary Works",
    "category": "Machinery & Equipment",
    "risk_description": "Injuries and death due to - Crushing, Entrapment etc",
    "who_harmed": "Working Party and others",
    "default_controls": "All Temporary Works must be approved by Temporary works co-ordinator or responsible person - Obtain permission from your supervisor before applying any load or force to any existing structures or surfaces.",
    "initial_likelihood": 4,
    "initial_severity": 5,
    "final_likelihood": 2,
    "final_severity": 5
  },
  {
    "id": "4ac7bfc9-2c91-5ee9-b129-e56419a4e770",
    "name": "Fork Lift Trucks (Including Telehandlers)",
    "category": "Machinery & Equipment",
    "risk_description": "Serious and fatal injuries Due to - Collision with FLT, crushing/collision due to dropped loads",
    "who_harmed": "Working Party and others",
    "default_controls": "Only personnel who hold a valid licence are permitted to operate Fork Lift  Trucks. Ensure a pre-use inspection of the equipment is carried out prior to use. Always adhere to the 3 Meter rule and remain constantly aware of your surroundings, a Banksman must be in place where necessary. If you leave the vehicle for any amount of time ensure the engine is switched off and keys  removed. Always operate within the safe working load of the vehicle. If a FLT or Telehandler is used to fit anything that is not palletised then a suitable lift plan must be created for the operation.",
    "initial_likelihood": 5,
    "initial_severity": 5,
    "final_likelihood": 1,
    "final_severity": 5
  },
  {
    "id": "b84b95be-c82c-55fe-9ea6-abf6ade21c91",
    "name": "Hand Tools",
    "category": "Machinery & Equipment",
    "risk_description": "Injuries due to faulty or incorrect use of tools - Cuts and abrasions, pinches, puncture wounds",
    "who_harmed": "Working Party",
    "default_controls": "Always use hand tools correctly and for their intended purpose, never improvise. Ensure they are free from damage and fit for purpose prior to use by carrying out a visual inspection of the tool, if any defects are found do not use and source a suitable replacement. Keep hand tools free from contaminates such as oil & grease that lead to loss of grip of the tool. Ensure tools such as wrenches and spanners are located correctly on the work piece before pressure is applied.  Wherever possible, ensure you use a tool specifically sized for the task, rather than an adjustable tool (Spanners etc.). When using striking tools e.g. sledge hammers, ensure that all persons are a safe distance away for the duration of the task.",
    "initial_likelihood": 3,
    "initial_severity": 3,
    "final_likelihood": 1,
    "final_severity": 3
  },
  {
    "id": "c6d35e2b-ac7f-5f6d-b193-191d6b7b57f5",
    "name": "Hydraulic Power",
    "category": "Machinery & Equipment",
    "risk_description": "Serious or fatal injuries caused by hydraulically powered plant and equipment.",
    "who_harmed": "Working Party and others",
    "default_controls": "Never carry out work on live plant or machinery. Ensure that suitable isolation controls are put in place prior to carrying out any works on hydraulic equipment. Raise any concerns with your supervisor. The supervisor will inform you when he is going to cancel the isolations, and from that moment on you must not return to that work area for any reason.",
    "initial_likelihood": 5,
    "initial_severity": 5,
    "final_likelihood": 1,
    "final_severity": 5
  },
  {
    "id": "7c7b536f-12c5-57ad-ad45-8e9990cfead5",
    "name": "Lift Operations",
    "category": "Machinery & Equipment",
    "risk_description": "Injuries, death or damage due to - Failure of equipment, loss of control of load etc.",
    "who_harmed": "Working party and others",
    "default_controls": "No lift should be carried out without an adequate lift plan being in place. Ensure all members of the working party involved with the lift have acknowledged and understood the contents of the lift plan. Ensure all lifting accessories are compliant. Avoid contact with suspend loads whenever possible, e.g. use push sticks / guide ropes. Never walk under suspended loads and keep non-essential personnel away from the area, establish an exclusion zone, consider physical barriers, signage and safety lookouts. All roles and responsibilities must be clearly defined and a suitable level of resource must be assigned. Employees are not permitted to assume multiple roles within the same operation.",
    "initial_likelihood": 5,
    "initial_severity": 5,
    "final_likelihood": 1,
    "final_severity": 5
  },
  {
    "id": "7d3b000e-10fc-58cb-97a2-453653794aa1",
    "name": "Metal striking activities – Hardened Steel against hardened steel",
    "category": "Machinery & Equipment",
    "risk_description": "Contact with ejected metal fragments/ shards travelling at velocity",
    "who_harmed": "Working party and others",
    "default_controls": "Ensure that you utilise ‘dollies,’ ‘drifts’ or other driving tools made of suitable materials\n(Brass, copper etc.) during striking operations.  Never stand in the ‘line of fire’ of potentially ejected objects.",
    "initial_likelihood": 4,
    "initial_severity": 3,
    "final_likelihood": 1,
    "final_severity": 3
  },
  {
    "id": "a2888638-1120-5fba-84cc-8facee43bbd2",
    "name": "Pneumatic Tools",
    "category": "Machinery & Equipment",
    "risk_description": "Injuries due to loss of control of the tool, compressed air, flying objects",
    "who_harmed": "Working Party and others",
    "default_controls": "When using pneumatic tools ensure you are familiar with the manufacturers instructions prior to use. Wear a suitable full-face shield (with safety glasses), appropriate gloves, footwear and hearing protection at all times. Erect screens to shield those who could enter the working area, employ a safety lookout if required. Ensure the tool is maintained according to manufacturers instructions, only use the recommended attachments. Be aware of your body position at all time to prevent hand, feet or body injuries if the tool slips or breaks. Support tool with a counterbalance where possible. Air Hose Safety: Use the proper hose and fittings of the correct diameter; Use hoses specifically designed to resist abrasion, cutting, crushing and failure from continuous flexing; Check hoses regularly for cuts, bulges and abrasions. Quarantine damaged hoses immediately; Blow out air line before connecting a tool; Make sure that connections fit properly and are equipped with a mechanical means of securing the connection; Install quick disconnects of a pressure-release type rather than a disengagement type. Attach the male end of the connector to the tool, NOT the hose; Do not operate at a pressure above manufacturer's rating; Turn off air pressure when not in use; Do not carry a tool by its hose; Ensure hoses are routed safely; Do not use compressed air to clean dirt from clothes.",
    "initial_likelihood": 4,
    "initial_severity": 4,
    "final_likelihood": 1,
    "final_severity": 4
  },
  {
    "id": "7cfaa471-fae6-53b6-a44f-3e5d5af33047",
    "name": "Powder Actuated Tools",
    "category": "Machinery & Equipment",
    "risk_description": "Serious and fatal injuries due to - Misuse or malfunction of tool",
    "who_harmed": "Working Party and Others",
    "default_controls": "Powder-actuated fastening tools, fasteners and charges must only be used according to the\nManufacturer’s Instruction. Only trained employees  or employees under direct supervision by a trained operator should use this type of equipment. The tool should be tested each day prior to use, to assure that safety devices and the tool itself are in proper working condition; The powder-actuated fastening tool must only be loaded at the place where it is intended to be used and immediately prior to its use. Never carry a loaded powder-actuated fastening tool, except when it cannot be unloaded because of mechanical failure. If the powder-actuated fastening tool has been loaded but is subsequently not used immediately, both the charge and fastener must be removed; Powder-actuated tools must not be used in areas where flammable or combustible atmospheres may be present. Press the tool firmly against the surface into which the fastening device is being driven, so the fastener will not glance off the surface; Never drive a fastener into a \"spalled\" or chipped surface, Do not drive fasteners into easily penetrated material unless that material is backed by an object that will prevent the fastener from passing completely through the material and creating a flying missile hazard on the other side. Never shoot into a surface unless you are certain it will contain the fastener.",
    "initial_likelihood": 5,
    "initial_severity": 5,
    "final_likelihood": 1,
    "final_severity": 5
  },
  {
    "id": "dd81b2a0-df81-5258-801b-360c2595110a",
    "name": "Pressure Systems",
    "category": "Machinery & Equipment",
    "risk_description": "Injuries due to defective equipment, unexpected release of pressure",
    "who_harmed": "Working Party and Others",
    "default_controls": "Always carry out a pre-use inspection of any pressure systems, report any defects to your supervisor immediately. Never use defective equipment. All pressure systems must be isolated prior to any maintenance activity. Always wear the relevant PPE when working with pressure systems.",
    "initial_likelihood": 5,
    "initial_severity": 4,
    "final_likelihood": 1,
    "final_severity": 4
  },
  {
    "id": "254e290d-4064-5932-b614-81ed084003ce",
    "name": "Rotating Equipment",
    "category": "Machinery & Equipment",
    "risk_description": "Injuries due to entrapment, crushing & fatality",
    "who_harmed": "Working Party",
    "default_controls": "Equipment must have its motive force isolated – electrically, pneumatically or hydraulically; a  certificate of isolation is required. Ensure all relevant permits have been obtained and any stored energy has been dissipated prior to starting work. Where practicable, physical prevention should installed.",
    "initial_likelihood": 4,
    "initial_severity": 5,
    "final_likelihood": 1,
    "final_severity": 5
  },
  {
    "id": "6185998b-39a1-57bd-806e-33a01de95ef2",
    "name": "Stored Energy",
    "category": "Machinery & Equipment",
    "risk_description": "Injuries sustained through contact with moving machinery",
    "who_harmed": "Working Party",
    "default_controls": "Ensure plant has been isolated and permits issued prior to starting work. Ensure any stored, potential or mechanical energy in a system has been dissipated or secured prior to starting any work. Ensure any latent energy in systems has been dissipated prior to starting work.",
    "initial_likelihood": 5,
    "initial_severity": 5,
    "final_likelihood": 2,
    "final_severity": 5
  },
  {
    "id": "427d3fae-34e1-5569-aca4-a7cc9c7cc960",
    "name": "Use of Jack Hammers / Hilti Drills",
    "category": "Machinery & Equipment",
    "risk_description": "Injuries due to flying objects, vibration exposure, loss of control of the tool",
    "who_harmed": "Working party and others",
    "default_controls": "Ensure you are familiar with the manufacturers instructions prior to use. Wear a suitable full-face shield (with safety glasses), appropriate gloves, footwear and hearing protection at all times. Erect screens to shield those who could enter the working area, employ a safety lookout if required. Ensure the tool is maintained according to manufacturers instructions, only use the recommended attachments. Be aware of your body position at all time to prevent hand, feet or body injuries if the tool slips or breaks. Support tool with a counterbalance where possible. Ensure vibration exposure is logged daily.",
    "initial_likelihood": 5,
    "initial_severity": 4,
    "final_likelihood": 1,
    "final_severity": 4
  },
  {
    "id": "579cbd76-7a1b-549a-9900-a014ea51f925",
    "name": "Use of Jacks (Hydraulic etc.)",
    "category": "Machinery & Equipment",
    "risk_description": "Failure of jack resulting in crush injuries, contact with ejected components of jacking arrangement",
    "who_harmed": "Working party and others",
    "default_controls": "Jacks to be used by competent employees.  Inspect jacks before use and ensure that all jack components are assembled correctly before the pressure is applied.  Ensure the surface on which the jack is placed is level, even and capable of taking the imposed loads.  Ensure that the head of the jack/ packer is in full, firm contact with the jacking point of the load at all times. Use packers if necessary, to prevent the head of the jack from slipping.  Raise and lower the load in a slow and steady manner – Never rush a jacking operation.  Never stand in the ‘line of fire’ of potentially ejected objects.",
    "initial_likelihood": 5,
    "initial_severity": 5,
    "final_likelihood": 2,
    "final_severity": 5
  },
  {
    "id": "f5c45122-4f8e-5440-9513-a67a98988707",
    "name": "Use of Knives/ Blades",
    "category": "Machinery & Equipment",
    "risk_description": "Lacerations due to contact with sharp edges",
    "who_harmed": "Working party",
    "default_controls": "Only use a knife or blade if there are no safer alternatives to complete the task (Concealed or guarded blades etc.).  Ensure that the blade or knife is strong enough for the task.  Suitable PPE must be worn at all times when using knives and blades - Suitable eye protection and cut-resistant gloves are mandatory.  Ensure blades are fully retracted when not in use and tools stored safely when not required.  Always work the tool away from your body and other people  Ensure tools are replaced if they become blunt or damaged.",
    "initial_likelihood": 5,
    "initial_severity": 3,
    "final_likelihood": 1,
    "final_severity": 3
  },
  {
    "id": "2d9ab95d-d0e8-5836-b74d-e47a30b65974",
    "name": "Use of Machinery",
    "category": "Machinery & Equipment",
    "risk_description": "Serious injury, burns, entrapment injuries, crushing injuries",
    "who_harmed": "Working Party and others",
    "default_controls": "Machinery should be kept in a efficient and maintained state and subject to regular preventative maintenance. All persons who use the machinery or supervise the use of machinery should have access to the relevant safety information such as written instructions and methods etc. Any persons using machinery should receive adequate training in it's use and purpose and carry out a pre-use inspection. Ensure all guards whether fixed or otherwise are in place and in good condition prior to use. Report any defects or malfunctions immediately, do not use any machinery that has defects or is malfunctioning. Be aware of any surface that may become hot due to the operation of the machine and ensure any LEV and extraction units are in a good state of repair and are functioning correctly.",
    "initial_likelihood": 4,
    "initial_severity": 5,
    "final_likelihood": 2,
    "final_severity": 5
  },
  {
    "id": "3f2ab85d-7e46-5105-8b34-78b242edd9c8",
    "name": "Use of Mobile Lifting Frames/ Portable Gantries",
    "category": "Machinery & Equipment",
    "risk_description": "Injuries, death or damage due to - Failure/ collapse of equipment, loss of control of load etc.",
    "who_harmed": "Working party and others",
    "default_controls": "All controls listed for associated Lift Operation Hazard must be in place.  Ensure that a valid thorough examination certificate is held for the equipment.  Lifting frame/ portable gantry must be erected/ assembled as per the instructions/ assembly manual, which must be available to the relevant employees and strictly followed with every assembly.  Ensure safe manual handling techniques are implemented throughout assembly period.  All technical specifications must be applied (Torque values etc.) during assembly.  Any equipment required to complete assembly (Torque wrenches etc.) must be calibrated if required.  The Working Load Limit for the equipment must be known to all and must never be exceeded.  Consider trial assemblies and trial lifts prior to deeming equipment fit-for-use if required.  Carry out a visual inspection of the equipment before each time it is used - If any damage or concern is noted, do not use and quarantine immediately.",
    "initial_likelihood": 5,
    "initial_severity": 5,
    "final_likelihood": 1,
    "final_severity": 5
  },
  {
    "id": "51f0c521-f618-54a0-b739-77a1b54a3d45",
    "name": "Welding",
    "category": "Machinery & Equipment",
    "risk_description": "Injuries due to - Burns, Arc Flash, Fumes, Fire, Hot Surfaces, Electrocution",
    "who_harmed": "Working party and others",
    "default_controls": "Ensure the area is inspected prior to hot works taking place, remove all combustible materials, protect any vulnerable equipment from damage with the use of appropriate fire blankets, if necessary douse the area prior to starting hot works. All leads must be routed with care to avoid a tripping hazard.\n\nEnsure the below are in place: \n\n•\tCompetent Fire Watch on all appropriate levels, fire watch must stay for 1 hour after hot works have finished\n•\tMeans of Extinguishing\n•\tScreens as required\n•\tAppropriate PPE\n•\tSuitable Respiratory Protective Equipment is MANDATORY                                                                                        •\tUtilise LEV (Portable units or fixed) where available and practical;                                                                                                                    •\tWhere possible, take steps to improve ventilation in the area - Consider natural and forced (Fans and air movers etc.) measures                                                       \n•\tCarry out pre-use inspection of all leads\n•\tEnsure Earth clamp is within 1.5M of welding operation",
    "initial_likelihood": 5,
    "initial_severity": 4,
    "final_likelihood": 1,
    "final_severity": 4
  },
  {
    "id": "09016bb3-30e0-51f2-aca7-ad24a5a338ba",
    "name": "Welding Sets",
    "category": "Machinery & Equipment",
    "risk_description": "Fire, Electrical Shock, Spillage, Burns",
    "who_harmed": "Working party and others",
    "default_controls": "Ensure set is earthed close to the job (1.5M of welding operation). Ensure spark arrestor is fitted. Inspect cables and set for condition pre-use. Fire extinguishers to be readily available. Drip tray to be placed beneath any fuel sets. Fuel to be stored in metal jerry cans, remote from areas of hot work, in a well ventilated area and clearly identified. Spill kits to be readily available. Route weld cables away from walkways and maintain good housekeeping. Be aware that parts of the welding set can become hot to touch, do not touch areas of the set that have become hot through constant use.",
    "initial_likelihood": 5,
    "initial_severity": 4,
    "final_likelihood": 1,
    "final_severity": 4
  },
  {
    "id": "018a810b-7755-5335-8709-85426b7e478f",
    "name": "Loading / Unloading Activities",
    "category": "Manual Handling",
    "risk_description": "Serious and fatal injuries Due to - Falling Objects, loss of control of load, collision with plant",
    "who_harmed": "Working Party and others",
    "default_controls": "Remember the three meter rule, do not move within three metres of mobile plant unless contact with the driver has been made and the mobile plant turned off. A banksman must be in place to control plant movements. When unloading lorries, use steps to access the lorry bed, a safety helmet AND a chin strap must be worn when working from a lorry bed. All drop zones and proposed load routes must be clearly identified and restricted. Ensure the driver and any non-essential personnel are in a safe location.",
    "initial_likelihood": 5,
    "initial_severity": 5,
    "final_likelihood": 1,
    "final_severity": 5
  },
  {
    "id": "7e2b66e0-bfe9-5e12-b4c7-ecfdf9f37606",
    "name": "Manual Handling",
    "category": "Manual Handling",
    "risk_description": "Strains, muscle injuries.  Dropped loads making contact with employees resulting in impact/ crush injuries",
    "who_harmed": "Working party and others",
    "default_controls": "Manual handling must be avoided whenever practicable – Mechanical lifting aids (FLT, cranes, trolleys etc.) must be utilised if available.  If MH unavoidable, the weight of the object to be handled or the force required to complete the task must be known and any proposed routes of travel must be inspected beforehand.  Team lifting can reduce the risk of injury if communication throughout is suitable and sufficient.  Suitable PPE must be worn during MH, with gloves that offer suitable grip (Welding gauntlets are NOT suitable).",
    "initial_likelihood": 4,
    "initial_severity": 4,
    "final_likelihood": 2,
    "final_severity": 4
  },
  {
    "id": "ddfcf77f-853f-5004-8cd8-ba977aa563d4",
    "name": "COVID-19 Coronavirus",
    "category": "Personal Safety",
    "risk_description": "Serious respiratory/health issues through infections virus",
    "who_harmed": "Working Party and others",
    "default_controls": "Good personal hygiene is essential. Frequently wash your hands with soap and water for 20 seconds, especially after blowing your nose, sneezing or coughing, before and after eating, on arrival at work and when you return home. Alternatively  use hand sanitiser as frequently as possible. Maintain social distance of at least two metres at all times, if this is not possible due to congested work areas or crowded welfare facilities etc, raise your concerns with your supervisor. Working within two meters is only permitted under 1 condition - If the work is absolutely essential and if all other avenues of carrying out the work have been explored so far as practicable. If working within two metres, then the correct PPE is mandatory – Disposable respirators rated FFP2 or above, work \"side-by-side\" wherever possible, \"face-to-face\" working should only be carried out for periods of fifteen minutes or less.  On-site vehicle usage is restricted to one person per vehicle whenever possible, where this is not possible then respirators should be worn at all times.  Regularly wipe down frequently-touched surfaces, items and other contact points with anti-bacterial wipes. This is especially important in shared spaces such as vehicles, mess rooms and workspaces and when items such as tools have to be shared.  It is mandatory to wear a face covering in all communal indoor/ enclosed spaces, such as offices, mess rooms and shared kitchens etc.  If you develop any symptoms i.e. a new continuous cough, a developing fever or a loss or change to your sense of smell or taste you must inform your supervisor, leave site immediately and then follow current government legislation.  You must isolate immediately if any member of your household displays symptoms or tests positive for coronavirus.  Please note:  Customer or site rules may dictate the additional controls are implemented – E.g. Wearing respirators in all situations.  However, controls listed here must always be complied with as a minimum.  Customer or site rules will be communicated to you by your supervisor and these must be complied with at all times.",
    "initial_likelihood": 5,
    "initial_severity": 5,
    "final_likelihood": 2,
    "final_severity": 5
  },
  {
    "id": "0e69988b-c8b8-54c5-a5d7-a2368a75f3fa",
    "name": "Flying / Ejected Objects",
    "category": "Personal Safety",
    "risk_description": "Injuries due to projectiles - Impact injuries, cuts and bruises.",
    "who_harmed": "Working Party and others",
    "default_controls": "Never stand in the ‘line of fire’ of potentially ejected objects. Always wear the correct PPE for the task you are carrying out. Use screens or barriers wherever possible. Ensure that the area around your work activates that have the potential to produce flying/ejected objects is cordoned off. Use appropriate signage where necessary. If you have any concerns raise them with your supervisor immediately.",
    "initial_likelihood": 4,
    "initial_severity": 4,
    "final_likelihood": 2,
    "final_severity": 4
  },
  {
    "id": "f8b7b58c-b526-50ba-8515-033f22420d65",
    "name": "Inadequate/ Incompetent Supervision",
    "category": "Personal Safety",
    "risk_description": "Risk of injury or ill health due to reduced hazard perception across the working party or failure to implement all required risk-control measures",
    "who_harmed": "Working Party",
    "default_controls": "Correct Supervisor resource allocated to all work activities.  This will consider chargehand, supervisor and senior supervisor level.  MII Engineering have established minimum qualifications for all supervisor levels, which will be implemented in all circumstances.  Roles and Responsibilities of supervisors have been established and documented, along with associated KPI targets for critical functions (Workplace Inspection Completion etc.)",
    "initial_likelihood": 5,
    "initial_severity": 5,
    "final_likelihood": 1,
    "final_severity": 5
  },
  {
    "id": "579385b7-4671-55b2-baa8-6c2722dcbb37",
    "name": "Lone Working",
    "category": "Personal Safety",
    "risk_description": "Injury as a result of lone-working/ lack of support.  Increase in injury-severity, due to treatment not being received within a suitable time-frame",
    "who_harmed": "Working Party",
    "default_controls": "High-risk work activities (Hot Work, Lift Operations, Work at Height, significant manual handling etc.) must not be carried out by lone-worker.  Suitable and sufficient reporting-in procedure must be established between employee and superior – Regular contact made by employee (hourly), if this contact is not received within the agreed period, supervisor must initiate contact/ search.",
    "initial_likelihood": 5,
    "initial_severity": 4,
    "final_likelihood": 1,
    "final_severity": 4
  },
  {
    "id": "26007c64-38f5-5b09-aac4-25a5f88d5728",
    "name": "Provision of first Aid",
    "category": "Personal Safety",
    "risk_description": "Delay in treatment to injuries",
    "who_harmed": "Working Party",
    "default_controls": "Ensure your aware of the first aid procedures in your work area e.g. location of site medical centre, identity of first aiders.",
    "initial_likelihood": 3,
    "initial_severity": 3,
    "final_likelihood": 1,
    "final_severity": 3
  },
  {
    "id": "5ef87668-7851-5a94-bf7f-31d986f81313",
    "name": "Sharp Edges",
    "category": "Personal Safety",
    "risk_description": "Cuts and abrasions",
    "who_harmed": "Working Party",
    "default_controls": "Avoid handling sharp objects wherever possible, use alternative methods of handling materials and objects such as trays, jigs, lift trucks etc. When handling material with sharp edges the appropriate PPE should be worn at all times.  Sharp edges on produced work should be de-burred, where sharp edges cannot be removed then the appropriate wrapping/padding should be used to cover the sharp edges. When using tools with exposed edges always ensure the tool is in good condition, always use the right tool for the job and always ensure the tool is replaced back into a protective covering or sheath.",
    "initial_likelihood": 4,
    "initial_severity": 3,
    "final_likelihood": 1,
    "final_severity": 3
  },
  {
    "id": "5e9532a8-608b-57c1-b554-67017eb2db02",
    "name": "Slips, Trips and Falls \\ Poor Housekeeping",
    "category": "Personal Safety",
    "risk_description": "Injuries relating to falls, impact injuries, muscular etc.",
    "who_harmed": "Working party and others",
    "default_controls": "Ensure housekeeping standards are maintained and kept at an acceptable level throughout the day. Adequately protect or re-route trailing leads. Ensure all equipment is returned to a storage area when not in use. Ensure that you look where you’re going at all times and maintain your full attention on any movement across site, particularly when approaching steps or changes in level.  Do not become distracted, as this increases the risk of fall.",
    "initial_likelihood": 4,
    "initial_severity": 3,
    "final_likelihood": 1,
    "final_severity": 3
  },
  {
    "id": "f91a07fe-d62f-5760-b2e0-03cbf32005c0",
    "name": "Trapping / Pinch Points",
    "category": "Personal Safety",
    "risk_description": "Injuries due to - Crushing, Entanglement",
    "who_harmed": "Working Party",
    "default_controls": "Always use the right tool for the job and identify any pinch or trapping points in your work area. Be aware of anything in your work area that has the potential to move and create pinch/trapping points. Never operate machinery without the appropriate machine guards in place. Always be aware of where you place your body especially if they are placed \"between\" any two moving or static objects.",
    "initial_likelihood": 3,
    "initial_severity": 5,
    "final_likelihood": 1,
    "final_severity": 5
  },
  {
    "id": "9aba3de2-5cfb-55b0-be88-4c05a544c733",
    "name": "Vermin / biological hazards",
    "category": "Personal Safety",
    "risk_description": "Diseases carried by vermin through vermin ablutions - Weil's disease, Psittacosis etc",
    "who_harmed": "Working Party and others",
    "default_controls": "Do not encourage the presence of Vermin, carefully dispose of waste food. Do not handle the carcasses of vermin with unprotected hands, where possible use a shovel or something similar. When working near water that may be infected, avoid any situations which may\nlead to inadvertent ingestion of water. Wear the protective equipment you are provided with. During work avoid rubbing your nose, mouth or eyes and cover all cuts/broken skin with plasters before starting work. Wash your hands thoroughly before eating, smoking and wash all other exposed skin upon completion of task and after handling any potentially contaminated clothing. Remove any wet protective clothing as soon as possible. Ensure rest breaks are taken away from the main working area. Ensure all contaminated waste is disposed of safely. Ensure suitable washing facilities are provided and an area where contaminated clothing can be stored separately to avoid cross contamination.",
    "initial_likelihood": 4,
    "initial_severity": 4,
    "final_likelihood": 1,
    "final_severity": 4
  },
  {
    "id": "03097465-7459-59f9-93b4-2d061a878799",
    "name": "Hazardous Surroundings & Environments",
    "category": "Site Specific",
    "risk_description": "Serious and fatal injuries as a result of Impaired Hazard Perception",
    "who_harmed": "Working party",
    "default_controls": "Always remain vigilant of your surroundings and be aware of frequent changes to your surroundings that could be a threat to your health and safety.  Only use mobile phones in designated areas. Please report any personal or professional sources of stress that may be distracting you. Always pay attention to other nearby work activities that may effect you. Physical stressors such as fatigue/tiredness, increased temperatures, high levels of noise etc can effect your decision making when in a hazardous environment.",
    "initial_likelihood": 5,
    "initial_severity": 5,
    "final_likelihood": 2,
    "final_severity": 5
  },
  {
    "id": "e3e6a88b-4b83-5698-acad-9724c1c71f9e",
    "name": "Oil and Grease",
    "category": "Site Specific",
    "risk_description": "Slips trips and falls, dermatitis",
    "who_harmed": "Working Party and Others",
    "default_controls": "It's important to monitor the condition of your work area at all times. Small spillages of oil and grease can be dealt with quickly by the working party, report large amounts of oil & grease spillages to your supervisor so cleaning measures can be taken. Where oil and grease cannot be avoided extra care should be taken to ensure a firm footing, pay particular attention to the state of your foot ware when your work involves climbing ladders, staircases and/or stepping over workplace fixtures or machinery parts (cable trays etc). Always wear gloves when working around oil and grease, wear disposable gloves underneath your regular gloves if necessary, this can cause sweating to remove the disposable gloves during break times to allow your hands to breath. Make use of barrier cream at every opportunity. Ensure your equipment remains free from oil and grease this can cause you to loose grip during operation. Remember to wash your hands before eating, drinking or smoking. Keep open wounds covered when working with oil and grease.",
    "initial_likelihood": 4,
    "initial_severity": 3,
    "final_likelihood": 1,
    "final_severity": 3
  },
  {
    "id": "863975ff-48db-55dd-ae8e-a467931ce5a9",
    "name": "Other Working Parties in the Area",
    "category": "Site Specific",
    "risk_description": "Injuries due to work activates of others in the area.",
    "who_harmed": "Working Party and Others",
    "default_controls": "Be aware of other working parties working in the same area, consider those working above and below you. Work should be planned in conjunction with other working parties with on-going communication to ensure safe operations at all times.",
    "initial_likelihood": 4,
    "initial_severity": 4,
    "final_likelihood": 2,
    "final_severity": 4
  },
  {
    "id": "ff9e1975-8fb8-5e72-a182-05036bcbdd56",
    "name": "Poor Ground Conditions",
    "category": "Site Specific",
    "risk_description": "Injuries pertaining to slips trips and falls.",
    "who_harmed": "Working Party",
    "default_controls": "If you feel ground conditions are not suitable in your work area e.g. uneven or slippery surfaces, ground shifting beneath your feet, raise your concerns with your supervisor immediately.",
    "initial_likelihood": 4,
    "initial_severity": 4,
    "final_likelihood": 2,
    "final_severity": 4
  },
  {
    "id": "047826ef-2437-59db-b6fd-c27ea1c4339d",
    "name": "Restricted Work Areas",
    "category": "Site Specific",
    "risk_description": "Injuries due to plant processes / moving machinery, falling objects, radiation exposure",
    "who_harmed": "Working Party",
    "default_controls": "Adhere to all warning signs and traffic light systems at all times. Do cross fixed or temporary barriers and do not bypass or interfere with guarding. If unsure, always seek permission to enter an area.",
    "initial_likelihood": 5,
    "initial_severity": 5,
    "final_likelihood": 2,
    "final_severity": 5
  },
  {
    "id": "2d4e64b5-680c-51b3-93fa-34e6f6db6d2f",
    "name": "Unauthorised or Inadequate Access and Egress",
    "category": "Site Specific",
    "risk_description": "Falls on same or different levels, injury from plant machinery",
    "who_harmed": "Working party",
    "default_controls": "Always stick to designated walkways where possible, maintain three points of contact when ascending or descending stairways. Adhere to all warning signage when entering plant areas. Ensure access to work areas is only achieved via designated and appropriate safe working platforms. When entering any area ensure you are aware of plant status. You must report any issues or concerns with access and egress – Stepping across openings, climbing over plant, making exaggerated steps up or down and walking up and down slopes is NOT Safe Access/ Egress.",
    "initial_likelihood": 3,
    "initial_severity": 5,
    "final_likelihood": 1,
    "final_severity": 5
  },
  {
    "id": "01b3b198-5ce3-537e-bb4a-8d67644e0965",
    "name": "Heavy plant and Road Traffic",
    "category": "Traffic & Vehicles",
    "risk_description": "Serious and fatal injuries due to collisions with moving plant & vehicles",
    "who_harmed": "Working Party",
    "default_controls": "Be aware of road traffic and heavy plant in your work area. Use designated crossings where possible otherwise ensure any crossing is completely clear of traffic before crossing. Wear appropriate PPE to ensure your are visible at all times. Always make eye contact with drivers of plant vehicles before entering their operating vicinity. Adhere to the three meter rule at all times. Adhere to local area rules, and site level crossing rules.",
    "initial_likelihood": 5,
    "initial_severity": 5,
    "final_likelihood": 1,
    "final_severity": 5
  },
  {
    "id": "d32c096d-97b5-5746-9da0-b3c6d989f947",
    "name": "On-Site Driving",
    "category": "Traffic & Vehicles",
    "risk_description": "Road Traffic Collisions",
    "who_harmed": "Working Party",
    "default_controls": "Always obey the law when driving any vehicle, always adhered to site specific rules when driving on a customer site and only park in designated areas. Never drive under the influence of drugs and/or alcohol. Ensure a weekly vehicle inspection is carried out on any vehicle under your control. If a vehicle you are driving is defective in an way, report to your supervisor immediately.",
    "initial_likelihood": 3,
    "initial_severity": 4,
    "final_likelihood": 1,
    "final_severity": 4
  },
  {
    "id": "4369d781-3037-5253-b8d9-905a2bceb263",
    "name": "Transport of Materials (Haulage)",
    "category": "Traffic & Vehicles",
    "risk_description": "Hitting structures\nLosing load\nOverloading",
    "who_harmed": "Working party and others",
    "default_controls": "Ensure load is within limits of haulage vehicle.  (i.e. weight and dimension).\n\nEnsure driver is aware of planned route and of any obstacles that need to be avoided.  (i.e. height and width).\n\nIf load is deemed to be oversize ensure relevant authorization has been obtained and Tata Works Protection Department has been made aware of movement.",
    "initial_likelihood": 5,
    "initial_severity": 4,
    "final_likelihood": 1,
    "final_severity": 4
  },
  {
    "id": "593c7017-a1ff-51d9-815f-56da863e3c85",
    "name": "MEWPS",
    "category": "Working at Height",
    "risk_description": "Serious and fatal injuries Due to - Collision with MEWP, Falls from Height, hot surfaces??",
    "who_harmed": "Working Party and others",
    "default_controls": "Ensure all relevant certification is provided and in place prior to use. Only trained and competent personnel permitted to operate MEWP. Ensure the Safe Working Load of the machine is displayed and adhered to, ensure a \"pre-flight\" check has been carried out and only use the platform and boom for the work for which it was intended. Ensure you keep your arms inside the confines of the platform while it's moving. Suitable barriers, cones, lights etc should be put in place to restrict access underneath when required. Ensure you wear a safety harness and that it is attached to the platform and that you wear all other relevant PPE. Moving parts must be adequately guarded and when the MEWP is not in use it should be immobilised at ground level. Ensure you have read and understood the rescue plan, raise any concerns with your supervisor.",
    "initial_likelihood": 5,
    "initial_severity": 5,
    "final_likelihood": 1,
    "final_severity": 5
  },
  {
    "id": "0b632820-e1c9-58a3-a645-fc8da956bbaa",
    "name": "Objects falling from above",
    "category": "Working at Height",
    "risk_description": "Contact with persons below, resulting in injury",
    "who_harmed": "Working party and others",
    "default_controls": "Maintain regular communication with relevant working parties above and below you.  Ensure barriers and warning signs are erected to prevent persons from walking under elevated work areas. Alternatively, a “look out” must be assigned to re – direct people from the area. Access into these areas must be restricted until the work has been completed or until the risk of falling objects has been eliminated. Maintain good housekeeping standards at all times, Suitable containers must be supplied to store loose objects, ensure toe-boards are in place around exposed edges, report any gaps or openings in elevated platforms immediately.",
    "initial_likelihood": 5,
    "initial_severity": 5,
    "final_likelihood": 2,
    "final_severity": 5
  },
  {
    "id": "d521c365-3cb1-509a-ab9e-d08b7a8a50dc",
    "name": "Scaffold",
    "category": "Working at Height",
    "risk_description": "Serious and fatal injuries due to - Falls from height, collapse of structure, falling objects",
    "who_harmed": "Working Party and others",
    "default_controls": "Fixed Scaffold\n\nScaffold must be planned according the requirements including loads, platforms, safe passage, access/egress, protection against weather etc. Scaffold should only be erected, adjusted and dismantled by a competent person. Do not tamper with scaffold and report any defects immediately. Ensure that any scaffold used holds a current and in-date Scaff tag, if scaffold is found to be out of compliance the Scaff tag must be removed. Always maintain three points of contact when traversing ladders, make use of mechanical means of transporting materials and tools too and from scaffold platforms. Never stretch or reach outside of a scaffold, whether it is fixed or mobile and always use designated access points. \n\nMobile Scaffold\n\nThe construction of mobile scaffold must only be carried out by those who hold a current certificate. Ensure a pre-use inspection is carried out prior to use and a formal inspection carried out every seven days by a competent person. Only use recognised access points.",
    "initial_likelihood": 5,
    "initial_severity": 5,
    "final_likelihood": 2,
    "final_severity": 5
  },
  {
    "id": "15089271-1589-52f3-979e-078e62702978",
    "name": "Use of Harnesses",
    "category": "Working at Height",
    "risk_description": "Injuries due to incorrect harness resulting in tension injuries, falls from height",
    "who_harmed": "Working party",
    "default_controls": "Ensure the correct harness is used for the task, if unsure seek advice from your supervisor. Harnesses must be regularly inspected by a competent person every six months. Harnesses must be stored in-line with manufactures guidelines when not in use. Harnesses must be visually inspected prior to use and recorded on a inspection checklist. Only attach your lanyard to approved anchor points, if you are unsure of approved anchor points raise your concerns with your supervisor. When using fall restraint harnesses the lanyard must be adjusted to ensure you do not leave the platform/carrier.",
    "initial_likelihood": 3,
    "initial_severity": 5,
    "final_likelihood": 1,
    "final_severity": 5
  },
  {
    "id": "8cc0ba0a-59ff-5faa-9439-1d32a34618e0",
    "name": "Use of Ladders",
    "category": "Working at Height",
    "risk_description": "Serious fatal injuries due to - falls from height, falling objects,",
    "who_harmed": "Working Party and others",
    "default_controls": "Always select a suitable ladder for the work activity. Pre-use inspections should be carried out prior to use. Ensure that the ladder is installed safely on a firm base and at the correct angle, remember the 1:4 ratio and never stand a ladder on a moveable platform such as a lift truck. Ladders should be used as a means of access and never as a working platform, the ladder must be safely secured near the top and extend it's landing platform by 1 meter. Ensure that only one person is on the ladders any one time, and never overload the ladder. Ensure the rungs are free from oil, grease etc and ensure you use adequate foot ware and it's free from oil, grease etc. Always maintain three points of contact when ascending/descending ladders, always face the ladder during this movement and take one rung at the time; never rush. Both hands must be kept free to hold the ladders, use tool bags, telehandlers etc to transport equipment to the required working platform. Never overreach from the ladder and never move the ladder while standing on the rungs. Ensure the ladder is stored correctly and  safely after use.",
    "initial_likelihood": 4,
    "initial_severity": 5,
    "final_likelihood": 1,
    "final_severity": 5
  },
  {
    "id": "d164249f-65bb-5c2b-b6c2-3d25fa587bcb",
    "name": "Use of Stepladders",
    "category": "Working at Height",
    "risk_description": "Serious fatal injuries due to - falls from height, falling objects,",
    "who_harmed": "Working Party and others",
    "default_controls": "Always select a suitable Stepladder for the work activity, consider the ladder material, safe working load, height of ladder etc. Pre-use inspections should be carried out prior to use. Ensure that the ladder is installed safely on a firm base and at the correct angle, never stand on a stepladder on a moveable platform such as a lift truck. You are only permitted to work from stepladders for short periods of time and only if all other practicable options have been exhausted. Ensure that only one person is on the ladders any one time, and never overload the ladder with anything that could cause it to become unbalanced or to exceed it's safe working load. Step ladders should be footed or otherwise secured when in use. Ensure the rungs are free from oil, grease etc and ensure you use adequate foot ware and it's free from oil, grease etc. Always maintain three points of contact when ascending/descending ladders, always face the ladder during this movement and take one rung at the time; never rush. Never overreach from the ladder and never move the ladder while standing on the rungs. Ensure the ladder is stored correctly and  safely after use.",
    "initial_likelihood": 4,
    "initial_severity": 5,
    "final_likelihood": 1,
    "final_severity": 5
  },
  {
    "id": "83746073-8f2d-5e42-95e8-6e7a32b90878",
    "name": "Work at height: existing platforms and walkways",
    "category": "Working at Height",
    "risk_description": "Fall from height",
    "who_harmed": "Working party and others",
    "default_controls": "Inspect platforms or walkways for signs of obvious damage or deterioration and report any defects immediately. Housekeeping to be maintained during activity and keep walkways clear. Use recognised access points only. Do not work outside, climb or stretch outside the confines of the working platform/gantry or walkway under any circumstances. If handrails or equipment is removed that creates an open edge, suitable edge protection scaffold must be erected immediately.",
    "initial_likelihood": 5,
    "initial_severity": 5,
    "final_likelihood": 1,
    "final_severity": 5
  },
  {
    "id": "97dd59ce-b54d-5078-bb6a-5d216ff53ad0",
    "name": "Working at Height",
    "category": "Working at Height",
    "risk_description": "Injuries or death due to - Falls from Height",
    "who_harmed": "Working party and others",
    "default_controls": "Ensure all open edges are suitably protected and suitable safe working platforms are in place. Instances where edge protection is not possible personal protective measures such as personal harnesses and lanyards must be used and connected to a designated and approved anchor point, inspect all equipment thoroughly before use and report any defects immediately. Do not use defective equipment under any circumstance. Scaffold must be checked by a competent person. Erect barriers or use covers to prevent falls through openings in the floor.",
    "initial_likelihood": 5,
    "initial_severity": 5,
    "final_likelihood": 2,
    "final_severity": 5
  }
];

const HAZARD_CATEGORIES = [
  "Chemical & Hazardous Substances",
  "Confined Space",
  "Electrical",
  "Environmental",
  "Excavation",
  "Fire & Hot Work",
  "Machinery & Equipment",
  "Manual Handling",
  "Personal Safety",
  "Site Specific",
  "Traffic & Vehicles",
  "Working at Height"
];
