// ═══════════════════════════════════════════════════════════
// MII RAMS Builder - Requirements Library
// Generated from desktop RAMSBuilder requirements_library.json
// ═══════════════════════════════════════════════════════════

const REQUIREMENTS_LIBRARY = {
  equipment: [
    { item: "Mobile Crane", safety_precaution: "The crane operator must hold a current license, the crane and all lifting equipment must have a current safety certificate for the duties to be performed; all non-essential personnel must clear the immediate area when loads are being lifted and transported to the work area. Area where the crane and lifting operation is to be barriered off where possible. Loads are not to be handled and the use of guide ropes, push and pull sticks must be used. It is only permissible to touch the load for final alignment. Lifting Operations and Lifting Equipment Regulations 1998 (LOLER) apply at all times, Lift Plan required and PICOLO must be nominated." },
    { item: "Gantry Crane / Pendent or Remote Operated", safety_precaution: "The operator must hold a current training licence and be approved by the site owner; daily pre-flight checks must be carried out; all non-essential personnel must clear of the immediate area when loads are being lifted and transported; a nominated banks-man will be in control of the lift. Loads are not to be handled and the use of guide ropes, push and pull sticks must be used. It is only permissible to touch the load for final alignment. All rigging activities must be carried out by a competent person, Mii POINT OF WORK LIFT PLAN book (SF011F) to be filled out for standard lifts, and a lift plan must be in place for any complex lifts. DAILY CHECKS AND CHECK SHEET MUST BE COMPLETED PRIOR TO OPERATION" },
    { item: "MEWP's (Mobile Elevating Work Platform)", safety_precaution: "The operator must hold a current training licence, safety harness must always be worn, and lanyard clipped on to MEWP's anchor point in the basket. If operated within a building where there is any gantry crane activity that could come into contact with the MEWP, then a (CSO) Crane Standing Orders permit must be taken out; The gantry crane driver must be informed when the platform is used in areas where it can be struck by the crane or its load, and the crane isolated prior to work commencing. Any other activities in the area must be coordinated to ensure safety is not compromised. The weather and floor conditions must also be considered before operation. Bolts, hand tools etc. to be kept in buckets to prevent items falling from height. An escape and rescue procedure must be in place in case of machine failure and/or an accident. A trained MEWP operator must be on the ground to lower the basket in an emergency. DAILY CHECKS AND CHECK SHEET MUST BE COMPLETED PRIOR TO OPERATION" },
    { item: "Safety Harnesses/Lanyards", safety_precaution: "Only trained personnel to use harnesses. Harness and lanyard to be inspected before use for any cuts, nicks or tears, broken fibres/cracks, overall deterioration, burnt, charred or melted fibres, rust or corrosion, missing straps fraying/abrasions. Every harness must have a legible tag identifying the harness, model, date of manufacture, name of manufacturer, limitations and warnings and a current colour inspection tag. Only use lanyards that are the suitable length and type for the task being undertaken. Harness and lanyards should be stored clean, dry and free of exposure to fumes, heat, direct ultra violet light, sunlight and corrosive elements." },
    { item: "Counter Balance Fork Truck / Telehandler", safety_precaution: "The operator must hold a current training licence, exercise extreme care when operating in confined areas; you must have a lift plan if a lifting attachment is used or carrying out a complex lift. A banksman is to accompany the machine when entering and leaving a building if the view is obstructed or whilst manoeuvred inside a building. The handbrake must be applied when stationary and ignition turned off, and keys removed when unattended. Also, do not parking on an incline. DAILY CHECKS AND CHECK SHEET MUST BE COMPLETED PRIOR TO OPERATION" },
    { item: "Lifting Equipment (slings, shackles, chain blocks)", safety_precaution: "All lifting equipment is to be certified and must have the current colour tag visible. All equipment is to be visual inspection before each use for any defects or missing parts. All rigging activities must be carried out by a competent person, Mii POINT OF WORK LIFT PLAN book (SF011F) to be filled out for standard lifts, and a lift plan must be in place for any complex lifts. An assessment of load is to be carried out prior to slinging and appropriate rigging equipment must be used. Loads are not to be handled and the use of guide ropes, push and pull sticks must be used. It is only permissible to touch the load for final alignment. Gloves to be worn when handling lifting equipment, any sharp edges of items to be slung must be protected. If you are unsure of any information required before lifting STOP and contact your supervisor before commencing. Lifting Operations and Lifting Equipment Regulations 1998 (LOLER) apply at all times." },
    { item: "Diesel Generators / Welding Sets / Compressors", safety_precaution: "All equipment must be visually inspected before use and have a current electrical safety test certificate. Generators must be switched off when not in use and the key removed if possible. Generators are only to be used inside a building if you have obtained permission, then they must be positioned so that the exhaust fumes are discharged safely to the outside. Spill kits to be available when re-fuelling. DAILY CHECKS MUST BE CARRIED OUT" },
    { item: "Welding Equipment", safety_precaution: "All equipment must be visually inspected before use, worn or damaged leads, tongs and earth clamps must be replaced. Welding cables must not pose a trip hazard and all care undertaken to minimise the risk. Welding screens to be deployed around the work area to minimise the risk of arc flash to adjacent personnel, welding earth to be no more than 1 meter away from the area where the welding is being undertaken. Fire blanket to be used where appropriate and suitable fire extinguishers to hand, also trained fire watch on standby at all times, and for 1 hour after any hot work has been carried out. All hot work to be undertaken according to Mii and Client Safe Working Procedure for Hot Work." },
    { item: "Flame Cutting Equipment", safety_precaution: "Fuel and oxygen bottles to be secured upright or on a suitable trolley. Flashback arrestors must be fitted to the regulators, visual inspection of equipment must be carried out before use, all equipment to be free from oil and grease. Appropriate PPE e.g. burning goggles/visor, gauntlets, fire retardant overalls to be worn. Fire blanket to be used where appropriate and suitable fire extinguishers to hand, also trained fire watch on standby at all times, and for 1 hour after any hot work has been carried out. All hot work to be undertaken according to Mii and Client Safe Working Procedure for Hot Work." },
    { item: "Abrasive Wheel Equipment (hand grinders)", safety_precaution: "Gloves, hearing protection, goggles/visor to be worn when operating equipment, ensure that the correct specification abrasive wheel is selected for the job, e.g. metal or stone, speed rating and correct diameter hole centre for spindle. Do not use an abrasive 'cutting' wheel for a grinding operation and vice versa. Do not undertake abrasive wheel work without ensuring other personnel are clear of the area or protected from the work. Equipment to be PA Tested and must be visually inspected before use. Report any suspect damage of disc or machine to supervisor, isolate the machine and mark the machine with a 'defective' tag. Abrasive wheel training required to change discs and discs must be in date. HOT WORK RULES APPLY. Do not operate the equipment in excess of its vibration exposure limit. HAV's" },
    { item: "Compressed Air Equipment", safety_precaution: "Only competent personnel to operate any compressed air equipment. Inspect hoses etc prior to each use and report any defective equipment to supervisor. Undertake risk assessments if using compressed air equipment in awkward places. Never run the equipment in excess of the safe working pressure. Air bags must not pose a trip hazard and all care undertaken to minimise the risk. Whips must be used when joining bags and tooling together. Never participate in horseplay with compressed air. Never point compressed air at other people. Do not operate the equipment in excess of its vibration exposure limit. HAV's" },
    { item: "Electrical/Battery Equipment (extension leads, lights)", safety_precaution: "Equipment to be PA Tested and must be visually inspected before use. Equipment is to be in good working order and only used in the way it was intended and for the purpose of the task. Report any suspected damage to your supervisor. Only competent trained personnel to operate equipment. Appropriate PPE to be used at all times. Electric leads must not pose a trip hazard and all care undertaken to minimise the risk. Batteries are to be returned on charge at the end of each shift. Do not operate the equipment in excess of its vibration exposure limit. HAV's" },
    { item: "Hand Tools", safety_precaution: "Appropriate PPE to be used at all times. Tools must be in good condition and free of grease and oil contamination. The correct tool is to be used for the application intended. Ensure hand tools are properly used and maintained. The Provision of Work Equipment Regulations 1998 (PUWER) A simple check by users of hand tools can control many risks, for example: Cutting tools - keep knives and blades sharp, cover exposed edges wherever possible. Hammers - avoid split, broken or loose shafts and worn or chipped heads. Make sure the heads are properly secured to the shafts. Files - these should have a proper handle. Never use them as levers. Chisels - the cutting edge should be sharpened to the correct angle. Do not allow the head of cold chisels to spread to a mushroom shape - grind off the sides regularly. Screwdrivers - never use them as chisels and never use hammers on them. Split handles are dangerous. Spanners - avoid splayed jaws. Scrap any which show signs of slipping. Have enough spanners of the right size. Do not improvise by using pipes etc. as extension handles." },
    { item: "Scaffolding", safety_precaution: "Must be erected by a competent scaffolder and fit for purpose, a Scaff tag identity label must be displayed at all times and be inspected at the beginning of every shift; defects must be reported to the scaffolding company and rectified before the scaffolding is used. Any scaffolding alterations must be undertaken by the scaffolding company only. Any loose boards, tubes or traps to be reported to your supervisor. The scaffolding is not to be overloaded and gangways kept clean at all times. Bolts, hand tools etc. to be kept in buckets to prevent items falling from height." },
    { item: "Gas Monitors (3 in 1 or better)", safety_precaution: "If working in a gas hazard area as defined in the PBS, then each member of the working party must carry a gas monitor. Gas awareness training must have been undertaken and the training in date. The monitor must be turned on and positioned on the chest near to where you breathe. The gas monitor must have current certification and the calibration must be in date. The dust filter on the front of the monitor must be checked regularly and changed when necessary. It is the responsibility of the user to make sure the monitor is charged and ready for use at the start of the shift. At the end of the shift return to stores. If the battery does run out, or the monitor malfunctions inform your PIOWP and leave the gas hazard area immediately and change over monitors." },
    { item: "Portable Ladders", safety_precaution: "Ladders must be inspected before use and in good condition. Must be secured at top or footed at bottom. 1:4 ratio for leaning ladders. Do not overreach - keep your belt buckle within the stiles. Three points of contact at all times when climbing. Do not use ladders for work of more than 30 minutes duration." },
    { item: "Pneumatic Tools", safety_precaution: "All equipment must be visually inspected before use. Hearing protection must be worn. Ensure air supply is clean and regulated. Whip checks must be fitted to all couplings. Do not operate the equipment in excess of its vibration exposure limit. HAV's" },
    { item: "GS38 Compliant Voltage Indicator", safety_precaution: "Must be GS38 compliant and within calibration date. Prove before and after use with approved proving unit. Inspect leads and probes for damage before each use. Do not use if damaged. Fused leads with finger guards and maximum 4mm exposed tip. Maximum voltage rating must exceed system voltage." },
    { item: "Voltage Indicator Proving Unit", safety_precaution: "Must be compatible with voltage indicator in use. Check proving unit is within calibration date. Prove voltage indicator immediately before and after testing as per GS38 requirements." },
    { item: "Insulated Tools (1000V Rated)", safety_precaution: "Must be rated to 1000V AC and comply with BS EN 60900. Inspect insulation for cracks, cuts, or damage before each use. Replace immediately if insulation is compromised. Do not use standard tools as substitutes. Store separately from non-insulated tools to prevent mix-ups." },
    { item: "Lock-Out/Tag-Out (LOTO) Equipment", safety_precaution: "Each person in the working party must apply their own personal safety lock. Locks must be uniquely identifiable to the individual. Record lock numbers on the permit to work. Do not remove another person's lock. Tags must clearly identify who applied the lock and the date/time." },
    { item: "Torque Wrench", safety_precaution: "Must be within calibration date and appropriate range for the application. Check calibration certificate before use. Do not use as a breaker bar. Store in case after use. Return to zero setting after use to preserve calibration." },
    { item: "Camera/Photography Equipment", safety_precaution: "Use for recording defects found during inspection. Ensure flash is safe for use in electrical environment. Do not use within arc flash boundary of energised equipment. Photographs must be date/time stamped and referenced to the asset and defect location." },
    { item: "Inspection Checklist/Recording Sheets", safety_precaution: "Use site-approved inspection checklist for recording findings. Complete all fields. Attach photographs of defects where applicable. Submit to supervisor on completion of task." },
    { item: "Megger/Insulation Resistance Tester", safety_precaution: "Must be within calibration date. Select correct test voltage for the equipment under test. Ensure circuit is de-energised and isolated before testing. Discharge any residual voltage after testing. Only competent electrical personnel to operate. Record results against asset ID." }
  ],

  coshh_substances: [
    { substance: "Oxygen", storage_requirements: "Bottles must be in good condition and fitted with flash back arresters and gauges. Locate in a well ventilated area on a trolley or secured vertically to ensure they cannot fall over. Bagging must be free of leaks and equipment to be free from oil and grease." },
    { substance: "Propane", storage_requirements: "Bottles must be in good condition and fitted with flash back arresters and gauges. Locate in a well ventilated area on a trolley or secured vertically to ensure they cannot fall over. Bagging must be free of leaks." },
    { substance: "Acetylene", storage_requirements: "Bottles must be stored upright and secured. Flash back arresters must be fitted. Store away from oxygen and heat sources. Never use at a rate exceeding 1/15th of cylinder contents per hour." },
    { substance: "Diesel", storage_requirements: "In well ventilated area in clearly labelled tanks and drums. Keep away from sources of heat and ignition. Avoid skin contact. Obey 'No Smoking' and 'Switch off engine' signs. Bowsers to be double skinned bunded type or in separate bund to 110% of tank capacity." },
    { substance: "Oil and Grease", storage_requirements: "Wear barrier cream and correct PPE, in particular suitable gloves and safety glasses. Maintain good housekeeping, any oil spillages to be cleared up with absorbent granules and disposed of in the correct oil bins. Grease to be cleaned up and disposed of immediately." },
    { substance: "CO2 and Argon", storage_requirements: "Bottles must be in good condition and fitted with flash back arresters and gauges. Locate in a well ventilated area on a trolley or secured vertically to ensure they cannot fall over. Bagging must be free of leaks. Asphyxiation risk in confined spaces." },
    { substance: "Welding Fumes", storage_requirements: "Ensure adequate ventilation or use LEV (Local Exhaust Ventilation). RPE may be required depending on materials being welded. For welding periods up to 1 hour in well ventilated areas, FFP3 masks can be used. For periods exceeding 1 hour, air-fed masks must be used." },
    { substance: "Cutting/Grinding Dust", storage_requirements: "Use dust extraction where possible. RPE (FFP3 minimum) required. Damp down to reduce airborne dust. Segregate work area where possible." },
    { substance: "Paints and Solvents", storage_requirements: "Store in original containers in well ventilated area. Keep away from ignition sources. Dispose of correctly. Check COSHH data sheet for specific PPE requirements." },
    { substance: "Adhesives and Sealants", storage_requirements: "Use in well ventilated areas. Store according to manufacturer's instructions. Wear appropriate PPE as per COSHH data sheet." }
  ],

  ppe: [
    { item: "Safety Helmet - Mandatory Hot Metal", standard: "CenturionS22WA Vulcan Heat Resistant White Safety Helmet" },
    { item: "Safety Boots - Mandatory Hot Metal", standard: "Conform to Standard EN ISO 20349:2010 Foundry Standard" },
    { item: "Overgarments - Mandatory Hot Metal", standard: "Conform to Standard EN ISO 11612 Molten Metal Suits MM2" },
    { item: "Undergarments - Mandatory Hot Metal", standard: "Conform to Standard EN ISO 11612:2015" },
    { item: "Safety Helmet - Mandatory Standard", standard: "Conform to Standard EN 397" },
    { item: "Safety Boots - Mandatory Standard", standard: "Conform to Standard EN 345-1:1993" },
    { item: "Overalls - Mandatory Standard", standard: "Conform to Standard EN ISO 11611 Alexandra/Proban Flameproof" },
    { item: "Safety Restraint Harness", standard: "Conform to Standard EN 361:2002" },
    { item: "Fall Restraint Lanyard", standard: "Conform to Standard EN 354:2002" },
    { item: "Double Fixed Lanyard", standard: "Conform to Standard EN 358:2002" },
    { item: "Fall Arrest Lanyard with Shock Absorber", standard: "Conform to Standard EN 355:2002" },
    { item: "Gloves - Cotton Chrome/Rigger", standard: "Conform to Standard EN420:2003" },
    { item: "Gloves - Cut Resistant", standard: "Conform to Standard EN 388:2016 Mechanical Hazards" },
    { item: "Gloves - Chemical Resistant", standard: "Conform to Standard EN 374:2016 Chemical Protection" },
    { item: "Safety Glasses - Mandatory", standard: "Conform to Standard EN166" },
    { item: "Ear Protection - Mandatory Above 85db", standard: "Conform to Standard EN351-1: 1993 PELTOR Optima III" },
    { item: "Hi-Viz Waistcoat - Flame retardant for hot work", standard: "Conform to Standard EN471" },
    { item: "Burning Goggles", standard: "Conform to Standard EN 166, EN 170, EN 175" },
    { item: "Welding/Burning Gauntlets", standard: "Conform to Standard EN407:2004" },
    { item: "Grinding Goggles", standard: "Conform to Standard EN 166:2001 Class 1" },
    { item: "Grinding Visor", standard: "Conform to Standard EN 166:2001" },
    { item: "Dust Mask FFP3 / Face Covering", standard: "Conform to Standard EN149: 2001" },
    { item: "Air Fed Welding Screen Headshield", standard: "Conform to Standard (APF 20) EN12941, P3, EN379 1/1/1/2" },
    { item: "Welding Ventilation", standard: "During welding, breathing apparatus must be worn. For welding for short periods (up to an hour) in well ventilated areas, (PPE) FFP3 masks can be used. Welding for periods in excess of 1 hour (RPE) airfed masks must be used." },
    { item: "3 in 1 Gas Monitor", standard: "B W Gas Alert Complies with EMC Directive 2004/108/EC" },
    { item: "Tinted Face Visor", standard: "Conform to Standard EN 1731:2006" },
    { item: "Coveralls", standard: "Conform to Standard EN 343 or above" },
    { item: "Knee Pads", standard: "Conform to Standard EN 14404:2004 Knee Protectors" },
    { item: "Emergency Escape Set (CF15/ELSA)", standard: "Conform to Standard EN 402:2003 Self-Contained Escape Units" },
    { item: "Arc Flash Rated Coveralls", standard: "Minimum 8 cal/cm2 arc rating for 415V LV work. Conform to Standard IEC 61482-2 / EN 61482-1-2. Must cover full body. Fasten all closures before entering arc flash boundary." },
    { item: "Arc Flash Rated Coveralls (HV)", standard: "Minimum 40 cal/cm2 arc rating for HV work. Conform to Standard IEC 61482-2 Class 2. Must cover full body. Fasten all closures before entering arc flash boundary." },
    { item: "Arc Flash Face Shield", standard: "Conform to Standard GS-ET-29 / ASTM F2178. Arc rating must match or exceed incident energy level. Must be worn with safety helmet. Full face and neck coverage required." },
    { item: "Arc Flash Balaclava", standard: "Conform to Standard IEC 61482-2. Arc rating must match or exceed incident energy level. Worn under safety helmet and face shield for full head/neck protection." },
    { item: "Insulated Gloves (Electrical)", standard: "Conform to Standard EN 60903. Class 00 (500V) minimum for LV work, Class 0 (1000V) for work up to 1kV. Must be tested within 6 months. Inspect for holes/tears before each use (air test). Wear leather over-gloves to protect against mechanical damage." }
  ]
};
